/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_bigfilhao;

import java.text.DecimalFormat;

/**
 *
 * @author Aluno
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtn1 = new javax.swing.JTextField();
        txtn2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        soma = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        div = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        expo = new javax.swing.JButton();
        raiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(350, 296));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setText("Número 1 ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setText("Número 2 ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        txtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 85, -1));
        getContentPane().add(txtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 85, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Operações");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 30));

        soma.setBackground(new java.awt.Color(255, 255, 255));
        soma.setText("+");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });
        getContentPane().add(soma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        sub.setBackground(new java.awt.Color(255, 255, 255));
        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 40, -1));

        mult.setBackground(new java.awt.Color(255, 255, 255));
        mult.setForeground(new java.awt.Color(240, 240, 240));
        mult.setText("*");
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });
        getContentPane().add(mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 50, -1));

        div.setBackground(new java.awt.Color(255, 255, 255));
        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        getContentPane().add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 80, 20));

        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, -1));

        expo.setBackground(new java.awt.Color(255, 255, 255));
        expo.setText("^");
        expo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expoActionPerformed(evt);
            }
        });
        getContentPane().add(expo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 50, -1));

        raiz.setBackground(new java.awt.Color(255, 255, 255));
        raiz.setText("Raiz");
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });
        getContentPane().add(raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
         String num1 = txtn1.getText();
        String num2 = txtn2.getText();
        double n1 = Double.parseDouble(num1);
        double n2 = Double.parseDouble(num2);
        double res=n1/n2;
        DecimalFormat df = new DecimalFormat("0.00");
        result.setText(""+ df.format(res));
    }//GEN-LAST:event_divActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        
    }//GEN-LAST:event_resultActionPerformed

    private void txtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtn1ActionPerformed
        
    }//GEN-LAST:event_txtn1ActionPerformed

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
        String num1 = txtn1.getText();
        String num2 = txtn2.getText();
        double n1 = Double.parseDouble(num1);
        double n2 = Double.parseDouble(num2);
        double res=n1+n2;
        DecimalFormat df = new DecimalFormat("0.00");
        result.setText(""+ df.format(res));
    }//GEN-LAST:event_somaActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        String num1 = txtn1.getText();
        String num2 = txtn2.getText();
        double n1 = Double.parseDouble(num1);
        double n2 = Double.parseDouble(num2);
        double res=n1-n2;
        DecimalFormat df = new DecimalFormat("0.00");
        result.setText(""+ df.format(res));
    }//GEN-LAST:event_subActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
         String num1 = txtn1.getText();
        String num2 = txtn2.getText();
        double n1 = Double.parseDouble(num1);
        double n2 = Double.parseDouble(num2);
        double res=n1*n2;
        DecimalFormat df = new DecimalFormat("0.00");
        result.setText(""+ df.format(res));
    }//GEN-LAST:event_multActionPerformed

    private void expoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expoActionPerformed
        String num1 = txtn1.getText();
        String num2 = txtn2.getText();
        double n1 = Double.parseDouble(num1);
        double n2 = Double.parseDouble(num2);
        double res=Math.pow(n1,n2);
        DecimalFormat df = new DecimalFormat("0.00");
        result.setText(""+ df.format(res));
    }//GEN-LAST:event_expoActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        String num1 = txtn1.getText();
        String num2 = txtn2.getText();
        double n1 = Double.parseDouble(num1);
        double n2 = Double.parseDouble(num2);
        double nn = 1/n2;
        double res=Math.pow(n1,nn);
        DecimalFormat df = new DecimalFormat("0.00");
        result.setText(""+ df.format(res));
    }//GEN-LAST:event_raizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton div;
    private javax.swing.JButton expo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mult;
    private javax.swing.JButton raiz;
    private javax.swing.JTextField result;
    private javax.swing.JButton soma;
    private javax.swing.JButton sub;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn2;
    // End of variables declaration//GEN-END:variables
}
