//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskTabuada.ServiceTabuada {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTabuada.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name TabuadaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabuada", ReplyAction="*")]
        DeskTabuada.ServiceTabuada.TabuadaResponse Tabuada(DeskTabuada.ServiceTabuada.TabuadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabuada", ReplyAction="*")]
        System.Threading.Tasks.Task<DeskTabuada.ServiceTabuada.TabuadaResponse> TabuadaAsync(DeskTabuada.ServiceTabuada.TabuadaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TabuadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabuada", Namespace="http://tempuri.org/", Order=0)]
        public DeskTabuada.ServiceTabuada.TabuadaRequestBody Body;
        
        public TabuadaRequest() {
        }
        
        public TabuadaRequest(DeskTabuada.ServiceTabuada.TabuadaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TabuadaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double num;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double modificador;
        
        public TabuadaRequestBody() {
        }
        
        public TabuadaRequestBody(double num, double modificador) {
            this.num = num;
            this.modificador = modificador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TabuadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TabuadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeskTabuada.ServiceTabuada.TabuadaResponseBody Body;
        
        public TabuadaResponse() {
        }
        
        public TabuadaResponse(DeskTabuada.ServiceTabuada.TabuadaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TabuadaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TabuadaResult;
        
        public TabuadaResponseBody() {
        }
        
        public TabuadaResponseBody(string TabuadaResult) {
            this.TabuadaResult = TabuadaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : DeskTabuada.ServiceTabuada.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<DeskTabuada.ServiceTabuada.WebServiceSoap>, DeskTabuada.ServiceTabuada.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeskTabuada.ServiceTabuada.TabuadaResponse DeskTabuada.ServiceTabuada.WebServiceSoap.Tabuada(DeskTabuada.ServiceTabuada.TabuadaRequest request) {
            return base.Channel.Tabuada(request);
        }
        
        public string Tabuada(double num, double modificador) {
            DeskTabuada.ServiceTabuada.TabuadaRequest inValue = new DeskTabuada.ServiceTabuada.TabuadaRequest();
            inValue.Body = new DeskTabuada.ServiceTabuada.TabuadaRequestBody();
            inValue.Body.num = num;
            inValue.Body.modificador = modificador;
            DeskTabuada.ServiceTabuada.TabuadaResponse retVal = ((DeskTabuada.ServiceTabuada.WebServiceSoap)(this)).Tabuada(inValue);
            return retVal.Body.TabuadaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeskTabuada.ServiceTabuada.TabuadaResponse> DeskTabuada.ServiceTabuada.WebServiceSoap.TabuadaAsync(DeskTabuada.ServiceTabuada.TabuadaRequest request) {
            return base.Channel.TabuadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeskTabuada.ServiceTabuada.TabuadaResponse> TabuadaAsync(double num, double modificador) {
            DeskTabuada.ServiceTabuada.TabuadaRequest inValue = new DeskTabuada.ServiceTabuada.TabuadaRequest();
            inValue.Body = new DeskTabuada.ServiceTabuada.TabuadaRequestBody();
            inValue.Body.num = num;
            inValue.Body.modificador = modificador;
            return ((DeskTabuada.ServiceTabuada.WebServiceSoap)(this)).TabuadaAsync(inValue);
        }
    }
}
