//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopProjeto.WebProjeto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebProjeto.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDepart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertDepart(int id, string nome, string local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDepart", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertDepartAsync(int id, string nome, string local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDependente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertDependente(int idf, int idd, string nome, string parente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDependente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertDependenteAsync(int idf, int idd, string nome, string parente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFunc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertFunc(int id, string nome, string end, string telefone, int salario, int idpto, int idptoger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertFuncAsync(int id, string nome, string end, string telefone, int salario, int idpto, int idptoger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertProj(int id, string nome, string tipo, string verba, int idpto, int cpffunc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProj", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertProjAsync(int id, string nome, string tipo, string verba, int idpto, int cpffunc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFuncProj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertFuncProj(int idf, int idp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFuncProj", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertFuncProjAsync(int idf, int idp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDependente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExcluiDependente(int id, int idf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDependente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiDependenteAsync(int id, int idf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDependente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateDependente(int id, string nome, string par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDependente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateDependenteAsync(int id, string nome, string par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDpto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExcluiDpto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDpto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiDptoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDpto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateDpto(int id, string nome, string local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDpto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateDptoAsync(int id, string nome, string local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFunc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExcluiFunc(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiFuncAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFunc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateFunc(int id, string nome, string end, string tel, int sal, int dp, int dpger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateFuncAsync(int id, string nome, string end, string tel, int sal, int dp, int dpger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiProjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExcluiProjeto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiProjetoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateProjeto(int id, bool conc, string nome, string tipo, string verba, int dp, int cdf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateProjetoAsync(int id, bool conc, string nome, string tipo, string verba, int dp, int cdf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProjetoIc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateProjetoIc(int id, bool conc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProjetoIc", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateProjetoIcAsync(int id, bool conc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFuncProjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateFuncProjeto(int idf, int idp, int aidf, int aidp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFuncProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateFuncProjetoAsync(int idf, int idp, int aidf, int aidp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFuncProjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExcluiFuncProjeto(int idf, int idp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFuncProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiFuncProjetoAsync(int idf, int idp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Departamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Departamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Departamento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DepartamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dependente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Dependente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dependente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DependenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Funcionario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Funcionario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Funcionario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> FuncionarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoAndamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ProjetoAndamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoAndamento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ProjetoAndamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoConcluido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ProjetoConcluido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoConcluido", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ProjetoConcluidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Projeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Projeto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Projeto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ProjetoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoAssociadoFunc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ProjetoAssociadoFunc(int proj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoAssociadoFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ProjetoAssociadoFuncAsync(int proj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoNaoAssociadoFunc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ProjetoNaoAssociadoFunc(int proj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProjetoNaoAssociadoFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ProjetoNaoAssociadoFuncAsync(int proj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DesktopProjeto.WebProjeto.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DesktopProjeto.WebProjeto.WebService1Soap>, DesktopProjeto.WebProjeto.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertDepart(int id, string nome, string local) {
            return base.Channel.InsertDepart(id, nome, local);
        }
        
        public System.Threading.Tasks.Task<bool> InsertDepartAsync(int id, string nome, string local) {
            return base.Channel.InsertDepartAsync(id, nome, local);
        }
        
        public bool InsertDependente(int idf, int idd, string nome, string parente) {
            return base.Channel.InsertDependente(idf, idd, nome, parente);
        }
        
        public System.Threading.Tasks.Task<bool> InsertDependenteAsync(int idf, int idd, string nome, string parente) {
            return base.Channel.InsertDependenteAsync(idf, idd, nome, parente);
        }
        
        public bool InsertFunc(int id, string nome, string end, string telefone, int salario, int idpto, int idptoger) {
            return base.Channel.InsertFunc(id, nome, end, telefone, salario, idpto, idptoger);
        }
        
        public System.Threading.Tasks.Task<bool> InsertFuncAsync(int id, string nome, string end, string telefone, int salario, int idpto, int idptoger) {
            return base.Channel.InsertFuncAsync(id, nome, end, telefone, salario, idpto, idptoger);
        }
        
        public bool InsertProj(int id, string nome, string tipo, string verba, int idpto, int cpffunc) {
            return base.Channel.InsertProj(id, nome, tipo, verba, idpto, cpffunc);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProjAsync(int id, string nome, string tipo, string verba, int idpto, int cpffunc) {
            return base.Channel.InsertProjAsync(id, nome, tipo, verba, idpto, cpffunc);
        }
        
        public bool InsertFuncProj(int idf, int idp, int hora) {
            return base.Channel.InsertFuncProj(idf, idp, hora);
        }
        
        public System.Threading.Tasks.Task<bool> InsertFuncProjAsync(int idf, int idp, int hora) {
            return base.Channel.InsertFuncProjAsync(idf, idp, hora);
        }
        
        public bool ExcluiDependente(int id, int idf) {
            return base.Channel.ExcluiDependente(id, idf);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiDependenteAsync(int id, int idf) {
            return base.Channel.ExcluiDependenteAsync(id, idf);
        }
        
        public bool UpdateDependente(int id, string nome, string par) {
            return base.Channel.UpdateDependente(id, nome, par);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDependenteAsync(int id, string nome, string par) {
            return base.Channel.UpdateDependenteAsync(id, nome, par);
        }
        
        public bool ExcluiDpto(int id) {
            return base.Channel.ExcluiDpto(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiDptoAsync(int id) {
            return base.Channel.ExcluiDptoAsync(id);
        }
        
        public bool UpdateDpto(int id, string nome, string local) {
            return base.Channel.UpdateDpto(id, nome, local);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDptoAsync(int id, string nome, string local) {
            return base.Channel.UpdateDptoAsync(id, nome, local);
        }
        
        public bool ExcluiFunc(int id) {
            return base.Channel.ExcluiFunc(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiFuncAsync(int id) {
            return base.Channel.ExcluiFuncAsync(id);
        }
        
        public bool UpdateFunc(int id, string nome, string end, string tel, int sal, int dp, int dpger) {
            return base.Channel.UpdateFunc(id, nome, end, tel, sal, dp, dpger);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFuncAsync(int id, string nome, string end, string tel, int sal, int dp, int dpger) {
            return base.Channel.UpdateFuncAsync(id, nome, end, tel, sal, dp, dpger);
        }
        
        public bool ExcluiProjeto(int id) {
            return base.Channel.ExcluiProjeto(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiProjetoAsync(int id) {
            return base.Channel.ExcluiProjetoAsync(id);
        }
        
        public bool UpdateProjeto(int id, bool conc, string nome, string tipo, string verba, int dp, int cdf) {
            return base.Channel.UpdateProjeto(id, conc, nome, tipo, verba, dp, cdf);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProjetoAsync(int id, bool conc, string nome, string tipo, string verba, int dp, int cdf) {
            return base.Channel.UpdateProjetoAsync(id, conc, nome, tipo, verba, dp, cdf);
        }
        
        public bool UpdateProjetoIc(int id, bool conc) {
            return base.Channel.UpdateProjetoIc(id, conc);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProjetoIcAsync(int id, bool conc) {
            return base.Channel.UpdateProjetoIcAsync(id, conc);
        }
        
        public bool UpdateFuncProjeto(int idf, int idp, int aidf, int aidp, int hora) {
            return base.Channel.UpdateFuncProjeto(idf, idp, aidf, aidp, hora);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFuncProjetoAsync(int idf, int idp, int aidf, int aidp, int hora) {
            return base.Channel.UpdateFuncProjetoAsync(idf, idp, aidf, aidp, hora);
        }
        
        public bool ExcluiFuncProjeto(int idf, int idp) {
            return base.Channel.ExcluiFuncProjeto(idf, idp);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiFuncProjetoAsync(int idf, int idp) {
            return base.Channel.ExcluiFuncProjetoAsync(idf, idp);
        }
        
        public System.Data.DataTable Departamento() {
            return base.Channel.Departamento();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DepartamentoAsync() {
            return base.Channel.DepartamentoAsync();
        }
        
        public System.Data.DataTable Dependente() {
            return base.Channel.Dependente();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DependenteAsync() {
            return base.Channel.DependenteAsync();
        }
        
        public System.Data.DataTable Funcionario() {
            return base.Channel.Funcionario();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> FuncionarioAsync() {
            return base.Channel.FuncionarioAsync();
        }
        
        public System.Data.DataTable ProjetoAndamento() {
            return base.Channel.ProjetoAndamento();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ProjetoAndamentoAsync() {
            return base.Channel.ProjetoAndamentoAsync();
        }
        
        public System.Data.DataTable ProjetoConcluido() {
            return base.Channel.ProjetoConcluido();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ProjetoConcluidoAsync() {
            return base.Channel.ProjetoConcluidoAsync();
        }
        
        public System.Data.DataTable Projeto() {
            return base.Channel.Projeto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ProjetoAsync() {
            return base.Channel.ProjetoAsync();
        }
        
        public System.Data.DataTable ProjetoAssociadoFunc(int proj) {
            return base.Channel.ProjetoAssociadoFunc(proj);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ProjetoAssociadoFuncAsync(int proj) {
            return base.Channel.ProjetoAssociadoFuncAsync(proj);
        }
        
        public System.Data.DataTable ProjetoNaoAssociadoFunc(int proj) {
            return base.Channel.ProjetoNaoAssociadoFunc(proj);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ProjetoNaoAssociadoFuncAsync(int proj) {
            return base.Channel.ProjetoNaoAssociadoFuncAsync(proj);
        }
    }
}
