<?php


class IndexView {
	
	private function gerar(){
		
		$html = "<!DOCTYPE html>";
		$html .= "<html>";
		$html .= "<head>";
		$html .= "<meta charset='UTF-8'>";
		$html .= "<!-- Meta Padrão -->";
		$html .= "<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>";
		$html .= "<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'>";
		$html .= "<!-- Propriedades do Site -->";
		$html .= "<title>S.A.G.A. - Sistema de Aprendizagem e Gestão Acadêmica</title>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/reset.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/site.css'>";
		$html .= "<link rel='stylesheet' href ='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/container.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/grid.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/header.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/image.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/menu.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/divider.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/dropdown.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/segment.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/button.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/list.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/icon.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/sidebar.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/transition.css'>";
		$html .= "<link rel='stylesheet' href='" . DOCUMENT_ROOT . "/public/css/index.css'>";
		$html .= "<!-- Scripts -->";
		$html .= "<script src='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/jquery-3.2.1.min.js'></script>";
		$html .= "<script src='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/visibility.js'></script>";
		$html .= "<script src='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/sidebar.js'></script>";
		$html .= "<script src='" . DOCUMENT_ROOT . "/public/lib/css/ui/dist/components/transition.js'></script>";
		$html .= "<script>";
		$html .= "$(document).ready(function() {";
		// Fixa o menu quando passa
		$html .= "$('.masthead').visibility({";
		$html .= "once: false, onBottomPassed: function() {";
		$html .= "$('.fixed.menu').transition('fade in');";
		$html .= "},";
		$html .= "onBottomPassedReverse: function() {";
		$html .= "$('.fixed.menu').transition('fade out');";
		$html .= "}";
		$html .= "});";
		// Cria barra lateral e acrescenta ao menu de abertura
		$html .= "$('.ui.sidebar').sidebar(";
		$html .= "'attach events', '.toc.item');";
		$html .= "});";
		$html .= "</script>";
		$html .= "</head>";
		$html .= "<body class='pushable'>";
		$html .= "<!-- Corpo do Menu -->";
		$html .= "<div class='ui large top fixed hidden menu'>";
		$html .= "<div class='ui container'>";
		$html .= "<a class='active item' href='#home''>Home</a>";
		$html .= "<a class='item' href='#objetivo'>Objetivo</a>";
		$html .= "<a class='item' href='#solicitar'>Conheça-nos</a>";
		$html .= "<div class='right menu'>";
		$html .= "<div class='item'>";
		$html .= "<a class='ui green button' href='". DOCUMENT_ROOT ."/Login/principal'>Entrar</a>";
		$html .= "</div>";
		$html .= "<div class='item'>";
		$html .= "<a class='ui red button' href='". DOCUMENT_ROOT ."/Principal/solicitar'>Solicitar</a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<!-- Menu Lateral -->";
		$html .= "<div class='ui vertical inverted sidebar menu left'>";
		$html .= "<a class='active item' href='#home'>Home</a>";
		$html .= "<a class='item' href='#objetivo'>Objetivo</a>";
		$html .= "<a class='item' href='#solicitar'>Conheça-nos</a>";
		$html .= "<a class='item' href='". DOCUMENT_ROOT ."/Login/principal'>Entrar</a>";
		$html .= "<a class='item' href='". DOCUMENT_ROOT ."/Principal/solicitar'>Solicitar</a>";
		$html .= "</div>";
		$html .= "<!-- Conteúdo da Página -->";
		$html .= "<!-- Parte 1 -->";
		$html .= "<div class='pusher' id='home'>";
		$html .= "<div class='ui inverted vertical masthead center aligned segment'>";
		$html .= "<div class='ui container'>";
		$html .= "<div class='ui large secondary inverted pointing menu'>";
		$html .= "<a class='toc item'> <i class='sidebar icon'></i> </a>";
		$html .= "<a class='active item' href='#home'>Home</a>";
		$html .= "<a class='item' href='#objetivo'>Objetivo</a>";
		$html .= "<a class='item' href='#solicitar'>Conheça-nos</a>";
		$html .= "<div class='right item'>";
		$html .= "<a class='ui inverted green button' href='". DOCUMENT_ROOT ."/Login/principal'>Entrar</a>";
		$html .= "<a class='ui inverted red button' href='". DOCUMENT_ROOT ."/Principal/solicitar'>Solicitar</a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= " <!-- Parte 2 -->";
		$html .= "<div class='ui text container'>";
		$html .= "<h1 class='ui inverted header'> S.A.G.A. </h1>";
		$html .= "<h2>Aquele que ajudará na sua saga.</h2>";
		$html .= "<a href='". DOCUMENT_ROOT ."/Login/principal'><div class='ui huge green button'>Acessar<i class=''></i></div></a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= " <!-- Parte 3 -->";
		$html .= "<div class='ui vertical stripe segment' id='objetivo'>";
		$html .= "<div class='ui middle aligned stackable grid container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='eight wide column'>";
		$html .= "<h3 class='ui header'>Objetivo do S.A.G.A.</h3>";
		$html .= "<p>Proporcionar aos alunos um software simples e completo, voltado para a vida acadêmica do aluno em uma instituição de ensino, que cooperará para o fornecimento de informações, avisos e programações voltadas a cada estudante da mesma, o S.A.G.A.</p>";
		$html .= "<h3 class='ui header'>Benefícios</h3>";
		$html .= "<p>Os benefícios são muitos, tanto para os alunos tanto para a instituição de ensino. O aluno receberá informações pertinentes ao curso e sua entidade acadêmica, ajudando em sua organização acadêmica e vida estudantil.</p>";
		$html .= "</div>";
		$html .= "<div class='seven wide right floated column'>";
		$html .= "<embed src='" . DOCUMENT_ROOT . "/public/video/pitchsaga.mp4' autostart='none' loop='true' width='563' height='317' class='video'></embed>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='row'>";
		$html .= "<div class='center aligned column'>";
		$html .= "<h1><i class='icon plus green'></i>Tempo</h1>";
		$html .= "<h1><i class='icon plus red'></i>Organização</h1>";
		$html .= "<h1><i class='icon plus orange'></i>Qualidade</h1>";
		$html .= "<h1><i class='icon plus blue'></i>Tranquilidade</h1>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= " <!-- Parte 4 -->";
		$html .= "<div class='ui vertical stripe segment' id='solicitar'>";
		$html .= "<div class='ui text container'>";
		$html .= "<h3 class='ui header'>Gostou? Conheça o S.A.G.A.</h3>";
		$html .= "<p>O S.A.G.A. é um sistema de aprendizagem e gestão acadêmica, que auxiliará tanto os alunos quanto a parte administrativa da escola. Os alunos serão beneficiados pelas diversas ferramentas que o software trás, como: tarefas a fazer, materiais de estudo cedido pelos professores, comunicados dos docentes ou do representante de sala, entre outras. Já a secretaria, por exemplo, poderá realizar o cadastro de alunos e alterações nos mesmos muito mais rapidamente.</p>";
		$html .= "<center><a class='ui large red button' href='". DOCUMENT_ROOT ."/Principal/solicitar'>CLIQUE AQUI E SOLICITE JÁ O SISTEMA</a></center>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<!-- Footer -->";
		$html .= "<div class='ui inverted vertical footer segment'>";
		$html .= "<div class='ui container'>";
		$html .= "<div class='ui stackable inverted divided equal height stackable grid'>";
		$html .= "<div class='three wide column'>";
		$html .= "<h4 class='ui inverted header'>Sobre</h4>";
		$html .= "<div class='ui inverted link list'>";
		$html .= "<a href='' class='item'>Sitemap</a>";
		$html .= "<a href='' class='item'>Contact Us</a>";
		$html .= "<a href='' class='item'>Religious Ceremonies</a>";
		$html .= "<a href='' class='item'>Gazebo Plans</a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='three wide column'>";
		$html .= "<h4 class='ui inverted header'>Serviços</h4>";
		$html .= "<div class='ui inverted link list'>";
		$html .= "<a href='' class='item'>Banana Pre-Order</a>";
		$html .= "<a href='' class='item'>DNA FAQ</a>";
		$html .= "<a href='' class='item'>How To Access</a>";
		$html .= "<a href='' class='item'>Favorite X-Men</a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='seven wide column'>";
		$html .= "<h4 class='ui inverted header'>Contato</h4>";
		$html .= "<a href='' class='item'><i class='icon facebook'></i>S.A.G.A.</a> <br>";
		$html .= "<a href='' class='item'><i class='icon instagram'></i>S.A.G.A.</a> <br>";
		$html .= "<a href='' class='item'><i class='icon google'></i>S.A.G.A.</a> <br>";
		$html .= "<a href='' class='item'><i class='icon youtube'></i>S.A.G.A.</a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</body>";
		$html .= "</html>";

		return $html;
	}
	
	public function mostrar(){
		echo $this->gerar();
	}
}