<?php

class Disciplina2View {
	
	private function gerar(){
		
		include_once "view/layout/header.php";
		$html .= "<div class='content-wrapper'>";
		$html .= "<!-- Main content -->";
		$html .= "<section class='content'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-md-12'>";
		$html .= "<div class='box'>";
		$html .= "<div class='box-header'>";
		$html .= "<h3 class='box-title'>";
		$html .= "<h1><i class='fa fa-book' id='icon_gerenciamento' aria-hidden='true'></i> Disciplina 2 (visão professor)</h1>";
		$html .= "<hr>";

		$html .= "<div class='box-body'>";

		$html .= "<ul class='nav nav-tabs' id='myTab' role='tablist'>";
		$html .= "<li class='nav-item active'>";
		$html .= "<a class='nav-link active' id='home-tab' data-toggle='tab' href='#home' role='tab' aria-controls='home' aria-selected='true'>Objetivo da Disciplina</a>";
		$html .= "</li>";
		$html .= "<li class='nav-item'>";
		$html .= "<a class='nav-link' id='profile-tab' data-toggle='tab' href='#profile' role='tab' aria-controls='profile' aria-selected='false'>Materiais</a>";
		$html .= "</li>";
		$html .= "<li class='nav-item'>";
		$html .= "<a class='nav-link' id='contact-tab' data-toggle='tab' href='#contact' role='tab' aria-controls='contact' aria-selected='false'>Realizar Chamada</a>";
		$html .= "</li>";
		$html .= "<li class='nav-item'>";
		$html .= "<a class='nav-link' id='nota-tab' data-toggle='tab' href='#nota' role='tab' aria-controls='nota' aria-selected='false'>Operações para Nota</a>";
		$html .= "</li>";
		$html .= "</ul>";
		$html .= "<div class='tab-content' id='myTabContent'>";
		$html .= "<div class='tab-pane fade active in' id='home' role='tabpanel' aria-labelledby='home-tab'>";
		$html .= "<br>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-12 col-md-12'>";
		$html .= "<a href='' id='btnListagem' style='width: 100%;' class='btn btn-primary' data-toggle='modal' data-target='#exampleModalObjetivoDisciplina'>";
		$html .= "Editar Informações";
		$html .= "</a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-12 col-md-12'>";
		$html .= "<h3>";
		$html .= "<strong class='text-primary'>Ementa da Disciplina</strong><br>";
		$html .= "<p class='text'>";
		$html .= "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
		$html .= "</p>";
		$html .= "<br>";
		$html .= "<strong class='text-primary'>Bibliografica Utilizada</strong><br>";
		$html .= "<p class='text'>";
		$html .= "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
		$html .= "</p>";
		$html .= "<br>";
		$html .= "<strong class='text-primary'>Disciplina Ministrada por: </strong><br>";
		$html .= "<p class='text'>";
		$html .= "<li>Renan Praxades</li>";
		$html .= "<li>Ciencias da Computação</li>";
		$html .= "<li>Unisanta</li>";
		$html .= "</p>";
		$html .= "</h3>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='tab-pane fade' id='profile' role='tabpanel' aria-labelledby='profile-tab'>";
		$html .= "<br>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-12 col-md-4'>";
		$html .= "<a href='' id='btnListagem2' style='width: 100%;' class='btn btn-primary' data-toggle='modal' data-target='#exampleModalAddMaterial'>";
		$html .= "Adicionar Material";
		$html .= "</a>";
		$html .= "</div>";
		$html .= "<div class='col-12 col-md-4'>";
		$html .= "<a href='' id='btnListagem2' style='width: 100%;' class='btn btn-primary' data-toggle='modal' data-target='#exampleModalEditMaterial'>";
		$html .= "Editar Material";
		$html .= "</a>";
		$html .= "</div>";
		$html .= "<div class='col-12 col-md-4'>";
		$html .= "<a href='' id='btnListagem2' style='width: 100%;' class='btn btn-primary' data-toggle='modal' data-target='#exampleModalDeleteMaterial1'>";
		$html .= "Retirar Material";
		$html .= "</a>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-12 col-md-12'>";
		$html .= "<h3>";
		$html .= "<strong class='text-primary'>Aula 01 - Assunto da Aula - Data</strong><br>";
		$html .= "<p class='text'>";
		$html .= "Material usado em sala (slides) (ppt ou atividade para fazer)";
		$html .= "</p>";
		$html .= "<i class='fa fa-download'><a href=''> Download</a></i>";
		$html .= "<br><br><br>";

		$html .= "<strong class='text-primary'>Aula 02 - Assunto da Aula - Data</strong><br>";
		$html .= "<p class='text'>";
		$html .= "Atividade para data (pdf com instruições e etc)";
		$html .= "</p>";
		$html .= "<i class='fa fa-download'><a href=''> Download</a></i>";
		$html .= "<br><br><br>";

		$html .= "<strong class='text-primary'>Aula 03 - Assunto da Aula - Data</strong><br>";
		$html .= "<p class='text'>";
		$html .= "Revisão P1";
		$html .= "</p>";
		$html .= "<i class='fa fa-download'><a href=''> Download</a></i>";
		$html .= "<br><br><br>";
		$html .= "</h3>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='tab-pane fade' id='contact' role='tabpanel' aria-labelledby='contact-tab'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-12 col-md-6'>";
		$html .= "<h3>";
		$html .= "<a href='' id='btnListagem2' style='width: 100%;' class='btn btn-success' data-toggle='modal' data-target='#exampleModalAula'>";
		$html .= "<i class='fa fa-plus'></i> Aula";
		$html .= "</a>";
		$html .= "</h3>";
		$html .= "</div>";
		$html .= "<div class='col-12 col-md-6'>";
		$html .= "<h3>";
		$html .= "<a href='' id='btnListagem2' style='width: 100%;' class='btn btn-success' data-toggle='modal' data-target='#exampleModalChamada'>";
		$html .= "<i class='fa fa-plus'></i> Chamada";
		$html .= "</a>";
		$html .= "</h3>";
		$html .= "<br>";
		$html .= "</div>";

		$html .= "<div class='container-fluid'>";
		$html .= "<table class='table' id='instituicoes_table'>";
		$html .= "<thead>";
		$html .= "<th class='col-md-6'>Aula</th>";
		$html .= "<th class='col-md-3'>Data</th>";
		$html .= "<th class='col-md-2'>Status</th>";
		$html .= "<th class='col-md-1 text-center'>Remover</th>";
		$html .= "</thead>";
		$html .= "<tbody>";
		$html .= "<tr>";
		$html .= "<td>Nome da Aula</td>";
		$html .= "<td>20/02/2018</td>";
		$html .= "<td class='text-danger'><i class='fa fa-times'></i> Em Aberto</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAula'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "<tr>";
		$html .= "<td>Nome da Aula</td>";
		$html .= "<td>20/02/2018</td>";
		$html .= "<td class='text-danger'><i class='fa fa-times'></i> Em Aberto</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAula'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "<tr>";
		$html .= "<td>Nome da Aula</td>";
		$html .= "<td>20/02/2018</td>";
		$html .= "<td class='text-success'><i class='fa fa-check'></i> Realizada</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAula'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "<tr>";
		$html .= "<td>Nome da Aula</td>";
		$html .= "<td>31/02/2018</td>";
		$html .= "<td class='text-success'><i class='fa fa-check'></i> Realizada</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAula'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "<tr>";
		$html .= "<td>Nome da Aula</td>";
		$html .= "<td>31/02/2018</td>";
		$html .= "<td class='text-success'><i class='fa fa-check'></i> Realizada</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAula'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "</tbody>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div class='tab-pane fade' id='nota' role='tabpanel' aria-labelledby='nota-tab'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-12 col-md-12'>";
		$html .= "<h3>";
		$html .= "<a href='' id='btnListagem' style='width: 100%;' class='btn btn-success' data-toggle='modal' data-target='#exampleModalAvaliacao'>";
		$html .= "<i class='fa fa-plus'></i> Atividade Avaliativa";
		$html .= "</a>";
		$html .= "</h3>";
		$html .= "<br>";
		$html .= "</div>";

		$html .= "<div class='container-fluid table-responsive'>";
		$html .= "<table class='table' id='users_table'>";
		$html .= "<thead>";
		$html .= "<th class='col-md-5'>Avaliacao</th>";
		$html .= "<th class='col-md-3'>Data</th>";
		$html .= "<th class='col-md-1'>Status</th>";
		$html .= "<th class='col-md-1 text-center'>Pontos</th>";
		$html .= "<th class='col-md-1 text-center'>Exibir</th>";
		$html .= "<th class='col-md-1 text-center'>Editar</th>";
		$html .= "<th class='col-md-1 text-center'>Apagar</th>";
		$html .= "</thead>";
		$html .= "<tbody>";
		$html .= "<tr>";
		$html .= "<td>Nome da Avaliacao</td>";
		$html .= "<td>20/02/2018</td>";
		$html .= "<td class='text-danger'><i class='fa fa-times'></i> Em Aberto</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-default' data-toggle='modal' data-target='#exampleModalNotasAvaliacao'><i class='fa fa-check-circle'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-info' data-toggle='modal' data-target='#exampleModalShowAvaliacao'><i class='fa fa-eye'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-warning' data-toggle='modal' data-target='#exampleModalEditAvaliacao'><i class='fa fa-pencil'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAvaliacao'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "<tr>";
		$html .= "<td>Nome da Avaliacao</td>";
		$html .= "<td>20/02/2018</td>";
		$html .= "<td class='text-danger'><i class='fa fa-times'></i> Em Aberto</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-default' data-toggle='modal' data-target='#exampleModalNotasAvaliacao'><i class='fa fa-check-circle'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-info' data-toggle='modal' data-target='#exampleModalShowAvaliacao'><i class='fa fa-eye'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-warning' data-toggle='modal' data-target='#exampleModalEditAvaliacao'><i class='fa fa-pencil'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAvaliacao'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "<tr>";
		$html .= "<td>Nome da Avaliacao</td>";
		$html .= "<td>20/02/2018</td>";
		$html .= "<td class='text-success'><i class='fa fa-check'></i> Realizada</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-default' data-toggle='modal' data-target='#exampleModalNotasAvaliacao'><i class='fa fa-check-circle'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-info' data-toggle='modal' data-target='#exampleModalShowAvaliacao'><i class='fa fa-eye'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-warning' data-toggle='modal' data-target='#exampleModalEditAvaliacao'><i class='fa fa-pencil'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAvaliacao'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "<tr>";
		$html .= "<td>Nome da Avaliacao</td>";
		$html .= "<td>31/02/2018</td>";
		$html .= "<td class='text-success'><i class='fa fa-check'></i> Realizada</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-default' data-toggle='modal' data-target='#exampleModalNotasAvaliacao'><i class='fa fa-check-circle'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-info' data-toggle='modal' data-target='#exampleModalShowAvaliacao'><i class='fa fa-eye'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-warning' data-toggle='modal' data-target='#exampleModalEditAvaliacao'><i class='fa fa-pencil'></i></a>";
		$html .= "</td>";
		$html .= "<td class='text-center'>";
		$html .= "<a href='' id='btnListagem' class='btn btn-danger' data-toggle='modal' data-target='#exampleModalDeleteAvaliacao'><i class='fa fa-trash'></i></a>";
		$html .= "</td>";
		$html .= "</tr>";
		$html .= "</tbody>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "<div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</section>";
		$html .= "</div>";
		include_once "view/layout/footer.php";
		include_once "view/disciplina/professor.php";
		return $html;
	}
	
	public function mostrar(){
		echo $this->gerar();
	}
}