<?php

class NotaDashboardView {
	
	private function gerar(){
		
		include_once "view/layout/header.php";


		$html .= "<style type='text/css'>";
		$html .= "*, *:before, *:after {";
		$html .= "-webkit-box-sizing: border-box;";
		$html .= "-moz-box-sizing: border-box;";
		$html .= "box-sizing: border-box;";
		$html .= "}";

		$html .= "/* regra para o clear float */";
		$html .= ".cf:before,";
		$html .= ".cf:after {content: '';display: table;}";
		$html .= ".cf:after {clear: both;}";
		$html .= ".cf {*zoom: 1;}";

		$html .= "#lateral:before {";
		$html .= "z-index:1000;";
		$html .= "content: url(icone-menu.png);";
		$html .= "font-size:4em;";
		$html .= "color:white;";
		$html .= "position:fixed;";
		$html .= "right:4px;";
		$html .= "top:45px;";
		$html .= "}";

		$html .= "#lateral:hover:before, #lateral:focus:before {";
		$html .= "right:500px";
		$html .= "}";

		$html .= "#lateral:hover, #lateral:focus,  #lateral:active  {";
		$html .= "overflow-y:scroll;";
		$html .= "-moz-transform: translate(-160px, 0);";
		$html .= "-webkit-transform: translate(-160px, 0);";
		$html .= "-o-transform: translate(-160px, 0);";
		$html .= "transform: translate(-160px, 0);";
		$html .= "padding-right:0;";
		$html .= "}";

		$html .= "#lateral .boxMenu {";
		$html .= "list-style-type:none;";
		$html .= "margin-bottom:1em;;";
		$html .= "padding-bottom:1em;";
		$html .= "}";

		$html .= "#lateral h3 {";
		$html .= "display:inline-block;";
		$html .= "font-weight:bold;";
		$html .= "font-size:1.6em;";
		$html .= "font-style:normal;";
		$html .= "padding-bottom:0.2em;";
		$html .= "padding-right: 50px;";
		$html .= "margin: 0.8em 0 1em 0.81em;";
		$html .= "color:rgb(255,255,255);";
		$html .= "border-bottom: 4px solid rgb(155,155,155);";
		$html .= "}";

		$html .= "#menu {";
		$html .= "font-style:italic;";
		$html .= "position:relative;";
		$html .= "font-size:1.0em;";
		$html .= "margin:2em -0.95em 1em -4.2em;";
		$html .= "padding:0;";
		$html .= "text-align: right;";
		$html .= "}";

		$html .= "#menu li { padding: 0px; margin: 0px; }";

		$html .= "#menu li a,  #menu li a:link {";
		$html .= "font-size:1.2em;";
		$html .= "color:rgb(255,255,255);";
		$html .= "text-decoration: none;";
		$html .= "padding: 0.8em 0 0.8em 0em;";
		$html .= "padding-right: 25px;";
		$html .= "margin-right: -11px;";
		$html .= "display: block;";
		$html .= "-moz-transition: all 1.2s ease;";
		$html .= "-webkit-transition: all 1.2s ease;";
		$html .= "-o-transition: all 1.2s ease;";
		$html .= "transition: all 1.2s ease;";
		$html .= "}";

		$html .= "#menu li a:hover {";
		$html .= "color:rgb(255,255,255);";
		$html .= "background-color:rgba(255,255,255,0.2);";
		$html .= "-moz-transition: all 0.5s ease;";
		$html .= "-webkit-transition: all 0.5s ease;";
		$html .= "-o-transition: all 0.5s ease;";
		$html .= "transition: all 0.5s ease;";
		$html .= "}";

		$html .= "@media (max-width: -500px) {";
		$html .= "body {margin-right:0;background-size:100% 28em!important;}";

		$html .= "#lateral {";
		$html .= "padding:0;";
		$html .= "-moz-transition: all 0.5s ease;";
		$html .= "-webkit-transition: all 0.5s ease;";
		$html .= "-o-transition: all 0.5s ease;";
		$html .= "transition: all 0.5s ease;";
		$html .= "font-size:1.2em;";
		$html .= "height:100%;";
		$html .= "overflow:auto;";
		$html .= "width:100%; ";
		$html .= "position:static;";
		$html .= "top:0;";
		$html .= "right:0;";
		$html .= "}";

		$html .= "#lateral:before {";
		$html .= "z-index:1000;";
		$html .= "width:0;";
		$html .= "text-align:center;";
		$html .= "content: '';";
		$html .= "font-size:0;";
		$html .= "color:white;";
		$html .= "position:static;";
		$html .= "top:0;";
		$html .= "right:0;";
		$html .= "display:inline-block; ";
		$html .= "}";

		$html .= "#lateral:hover, #lateral:focus {";
		$html .= "overflow:scroll;";
		$html .= "-moz-transform: none;";
		$html .= "-webkit-transform: none;";
		$html .= "-o-transform:none;";
		$html .= "transform:none;";
		$html .= "}";

		$html .= "#menu li a {border-bottom:1px solid #ccc;}";
		$html .= "#menu li:first-child a {border-top:1px solid #ccc;}  ";
		$html .= "</style>";



		$html .= "<!-- Content Wrapper. Contains page content -->";
		$html .= "<div class='content-wrapper'>";
		$html .= "<!-- Main content -->";
		$html .= "<section class='content'>";

		$html .= "<div class='row'>";
		$html .= "<div class='col-md-12'>";
		$html .= "<div class='box'>";
		$html .= "<div class='box-header'>";
		$html .= "<h3 class='box-title'>";
		$html .= "<h1><i class='fa fa-check-circle' aria-hidden='true'></i> Notas</h1>";
		$html .= "<hr>";
		$html .= "</h3>";
		$html .= "</div>";
		$html .= "<div class='box-body'>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina1'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 1</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-success text-center' colspan='3'><h3>10</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina2'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 2</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<td>Nome da Avaliação</td>";
		$html .= "<th>Nota</th>";
		$html .= "<td>10</td>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-success text-center' colspan='3'><h3>10</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";


		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina3'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 3</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>1</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>2</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>3</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>4</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-danger text-center' colspan='3'><h3>2.5</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina4'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 4</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>1</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>2</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>3</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>4</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-danger text-center' colspan='3'><h3>2.5</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina5'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 5</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>1</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>2</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>3</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>4</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-danger text-center' colspan='3'><h3>2.5</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina6'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 6</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>1</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>2</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>3</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>4</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-danger text-center' colspan='3'><h3>2.5</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina7'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 7</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>1</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>2</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>3</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>4</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-danger text-center' colspan='3'><h3>2.5</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina8'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 8</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>1</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>2</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>3</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>4</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-danger text-center' colspan='3'><h3>2.5</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "<div class='jumbotron jumbotron-fluid' id='disciplina9'>";
		$html .= "<div class='container'>";
		$html .= "<div class='row'>";
		$html .= "<div class='col-6 col-md-4'>";
		$html .= "<h1 class='display-4'>Disciplina 9</h1>   ";
		$html .= "</div>";
		$html .= "<div class='col-6 col-md-6'>";
		$html .= "<table class='table table-responsive table-hover'>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>1</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>2</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>3</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th>Avaliação</th>";
		$html .= "<th>Nome da Avaliação</th>";
		$html .= "<th>Nota</th>";
		$html .= "<th>4</th>";
		$html .= "</thead>";
		$html .= "<thead>";
		$html .= "<th class='text-center text-success'><h3>Media Final</h3></th>";
		$html .= "<th class='text-danger text-center' colspan='3'><h3>2.5</h3></th>";
		$html .= "</thead>";
		$html .= "</table>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</div>";

		$html .= "</div>";
		$html .= "</div>";

		$html .= "</div>";
		$html .= "<div id='lateral' class='col-md-1' ";
		$html .= "style='";


		$html .= "margin-right: 0px; /* espaço à esquerda para a barra vertical vísivel do menu */";
		$html .= "font:  52.5%/1.2 Verdana, Helvetica, Arial, sans-serif;";

		$html .= "padding:60px 130px 0px 0px;";
		$html .= "-moz-transition: all 0.5s ease;";
		$html .= "-webkit-transition: all 0.5s ease;";
		$html .= "-o-transition: all 0.5s ease;";
		$html .= "transition: all 0.5s ease;";
		$html .= "font-size:1em;";
		$html .= "background:rgb(44,62,80);";
		$html .= "background-image: -moz-linear-gradient(135deg, rgb(3,8,12), rgb(16,57,79));";
		$html .= "background-image: -webkit-linear-gradient(135deg, rgb(3,8,12), rgb(16,57,79));";
		$html .= "background-image: -o-linear-gradient(135deg, rgb(3,8,12), rgb(16,57,79) );";
		$html .= "background-image: -ms-linear-gradient(135deg, rgb(3,8,12), rgb(16,57,79));";
		$html .= "background-image: linear-gradient(135deg, rgb(3,8,12), rgb(16,57,79));";
		$html .= "height:100%;";
		$html .= "overflow:hidden;";
		$html .= "width:320px; ";
		$html .= "position:fixed;";
		$html .= "top:0;";
		$html .= "right:-285px;";


		$html .= "'>";
		$html .= "<div id='menu'>";
		$html .= "<h3 class='link-titulo'><i class='fa fa-angle-double-left' style='margin-right: 15px;'> </i> Disciplinas</h3>";
		$html .= "<ul class='boxMenu'>          ";
		$html .= "<li><a href='#disciplina1'>Matematica</a></li>";
		$html .= "<li><a href='#disciplina2'>Portugues</a></li>";
		$html .= "<li><a href='#disciplina3'>Astronomia</a></li>";
		$html .= "<li><a href='#disciplina4'>Educacao Fisica</a></li>";
		$html .= "<li><a href='#disciplina5'>Geografia</a></li>";
		$html .= "<li><a href='#disciplina6'>Historia</a></li>";
		$html .= "<li><a href='#disciplina7'>Filosofia</a></li>";
		$html .= "<li><a href='#disciplina8'>Fisica</a></li>";
		$html .= "<li><a href='#disciplina9'>Educacao Artistica</a></li>";
		$html .= "</ul>";
		$html .= "</div> <!-- /#menu -->";
		$html .= "</div>";
		$html .= "</div>";
		$html .= "</section>";
		$html .= "</div>";
		include_once "view/layout/footer.php";

		return $html;
	}
	
	public function mostrar(){
		echo $this->gerar();
	}
}