
import javax.swing.JOptionPane;

/*
 Na loja de produtos de informática – next: o sistema fornece as seguintes opções:
1. Calcular total dos produtos
2. Calcular o troco
3. Ajuda
4. Lista de produtos
5. Sair
Crie o programa acima utilizando entrada e saída de dados JoptionPane e interface gráfica JFrame.
 */

/**
 *
 * @author Aluno
 */
public class RM04757 extends javax.swing.JFrame {

    /**
     * Creates new form RM04757
     */
    public RM04757() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_calctotalproduto = new javax.swing.JButton();
        btn_calctroco = new javax.swing.JButton();
        btn_ajuda = new javax.swing.JButton();
        btn_listaprodutos = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_calctotalproduto.setText("1. Calcular Total dos Produtos");
        btn_calctotalproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calctotalprodutoActionPerformed(evt);
            }
        });

        btn_calctroco.setText("2. Calcular o Troco");
        btn_calctroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calctrocoActionPerformed(evt);
            }
        });

        btn_ajuda.setText("Ajuda");
        btn_ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajudaActionPerformed(evt);
            }
        });

        btn_listaprodutos.setText("3. Lista de Produtos");
        btn_listaprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaprodutosActionPerformed(evt);
            }
        });

        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_sair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_calctotalproduto)
                            .addComponent(btn_calctroco)
                            .addComponent(btn_listaprodutos)
                            .addComponent(btn_ajuda))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_calctotalproduto)
                .addGap(18, 18, 18)
                .addComponent(btn_calctroco)
                .addGap(18, 18, 18)
                .addComponent(btn_listaprodutos)
                .addGap(18, 18, 18)
                .addComponent(btn_ajuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addContainerGap())
        );

        btn_calctotalproduto.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calctotalprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calctotalprodutoActionPerformed
        int i=0;
        double valor = 0, valortt = 0;
        do
        {
            valor = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor do produto (DIGITE '0' PARA SAIR): "));
            if(valor==0){
                i = 1;
            }
            else{
                valortt = valortt + valor;
            }
        }while(i==0);
        JOptionPane.showMessageDialog(null, "O valor total será R$ " + valortt);
    }//GEN-LAST:event_btn_calctotalprodutoActionPerformed

    private void btn_ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajudaActionPerformed
        JOptionPane.showMessageDialog(null, "Opções: \n 1. Para calcular o valor de produtos que serão introduzidos "
                + "pelo usuário \n 2. Para calcular troco que será calculado a partir dos valores digitados pelo usuário "
                + "mais o valor que deverá ser pago pelo usuário"
                + "\n 3. Para ver uma listagem de produtos \n SAIR - sair do programa" );
    }//GEN-LAST:event_btn_ajudaActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_calctrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calctrocoActionPerformed
        int i=0;
        double valor = 0, valortt = 0, gastar = 0;
        do
        {
            valor = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor do produto (DIGITE '0' PARA SAIR): "));
            if(valor==0){
                i = 1;
            }
            else{
                valortt = valortt + valor;
            }
        }while(i==0);
        gastar = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor que deverá pago (DIGITE '0' PARA SAIR): "));
        double troco = valortt - gastar;
        JOptionPane.showMessageDialog(null, "O valor total do troco será R$ " + troco);
    }//GEN-LAST:event_btn_calctrocoActionPerformed

    private void btn_listaprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaprodutosActionPerformed
        JOptionPane.showMessageDialog(null, "Opções: \n 1. R$ 1500.00 XBOX 360"
                + "\n 2. R$ 2500.00 XBOX ONE "
                + "\n 3. R$ 3000.00 PC GAMER"
                + "\n 4. R$ 500.00 PLACA DE VÍDEO GTX 1050"
                + "\n 5. R$ 1000.00 PROCESSADOR INTEL CORE i7"
                + "\n 6. R$ 1000.00 PSP"
                + "\n 7. R$ 2800.00 PS4"
                + "\n 8. R$ 1800.00 PS3" );
    }//GEN-LAST:event_btn_listaprodutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RM04757.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RM04757.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RM04757.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RM04757.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RM04757().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajuda;
    private javax.swing.JButton btn_calctotalproduto;
    private javax.swing.JButton btn_calctroco;
    private javax.swing.JButton btn_listaprodutos;
    private javax.swing.JButton btn_sair;
    // End of variables declaration//GEN-END:variables
}
