/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forca;

/**
 *
 * @author Aluno
 */
public class AForca extends javax.swing.JFrame {

    /**
     * Creates new form AForca
     */
    public AForca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabeca = new javax.swing.JLabel();
        tronco = new javax.swing.JLabel();
        maodireita = new javax.swing.JLabel();
        maoesquerda = new javax.swing.JLabel();
        peesquerdo = new javax.swing.JLabel();
        pedireito = new javax.swing.JLabel();
        lbl_forca = new javax.swing.JLabel();
        lbl_letra = new javax.swing.JLabel();
        txtletra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpalavra = new javax.swing.JTextField();
        lbl_palavra = new javax.swing.JLabel();
        btnenter = new javax.swing.JButton();
        btnpalavra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        cabeca.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        cabeca.setText("O");

        tronco.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        tronco.setText("|");

        maodireita.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        maodireita.setText("_");

        maoesquerda.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        maoesquerda.setText("_");

        peesquerdo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        peesquerdo.setText("/");

        pedireito.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        pedireito.setText("\\");

            lbl_forca.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
            lbl_forca.setText("Jogo da Forca");

            lbl_letra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
            lbl_letra.setText("Digite uma letra:");

            txtletra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            txtletra.setName(""); // NOI18N
            txtletra.setPreferredSize(new java.awt.Dimension(6, 28));
            txtletra.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtletraActionPerformed(evt);
                }
            });

            jLabel2.setBackground(new java.awt.Color(153, 153, 153));
            jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(51, 51, 51));

            txtpalavra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

            lbl_palavra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            lbl_palavra.setText("Digite a palavra:");

            btnenter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnenter.setText("ENTER");
            btnenter.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnenterActionPerformed(evt);
                }
            });

            btnpalavra.setText("CONFIRMAR");
            btnpalavra.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnpalavraActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(lbl_forca)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(maoesquerda)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(tronco)
                                    .addGap(10, 10, 10)
                                    .addComponent(maodireita))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(cabeca)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(peesquerdo)
                            .addGap(18, 18, 18)
                            .addComponent(pedireito)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtpalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnpalavra)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtletra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_letra))
                                .addComponent(lbl_palavra)
                                .addComponent(btnenter))
                            .addGap(36, 36, 36))))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(lbl_forca)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cabeca)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tronco))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(maoesquerda))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(maodireita)))
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(peesquerdo)
                                        .addComponent(pedireito))))
                            .addGap(20, 20, 20))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(lbl_letra)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnenter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_palavra)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnpalavra)
                                .addComponent(txtpalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtletraActionPerformed
        
    }//GEN-LAST:event_txtletraActionPerformed

    private void btnpalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpalavraActionPerformed
       String palavra= txtpalavra.getText();
       txtpalavra.setText("");
       txtpalavra.disable();
       btnpalavra.disable();
       return palavra;
    }//GEN-LAST:event_btnpalavraActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
        String letra = txtletra.getText();
        btnpalavraActionPerformed(String palavra);
        if(txtletra.equals(palavra)){
            
        }
            
    }//GEN-LAST:event_btnenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AForca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnpalavra;
    private javax.swing.JLabel cabeca;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_forca;
    private javax.swing.JLabel lbl_letra;
    private javax.swing.JLabel lbl_palavra;
    private javax.swing.JLabel maodireita;
    private javax.swing.JLabel maoesquerda;
    private javax.swing.JLabel pedireito;
    private javax.swing.JLabel peesquerdo;
    private javax.swing.JLabel tronco;
    private javax.swing.JTextField txtletra;
    private javax.swing.JTextField txtpalavra;
    // End of variables declaration//GEN-END:variables
}
