//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopProjeto.WebProjeto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebProjeto.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDepart", ReplyAction="*")]
        DesktopProjeto.WebProjeto.InsertDepartResponse InsertDepart(DesktopProjeto.WebProjeto.InsertDepartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDepart", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertDepartResponse> InsertDepartAsync(DesktopProjeto.WebProjeto.InsertDepartRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDependente", ReplyAction="*")]
        DesktopProjeto.WebProjeto.InsertDependenteResponse InsertDependente(DesktopProjeto.WebProjeto.InsertDependenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDependente", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertDependenteResponse> InsertDependenteAsync(DesktopProjeto.WebProjeto.InsertDependenteRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFunc", ReplyAction="*")]
        DesktopProjeto.WebProjeto.InsertFuncResponse InsertFunc(DesktopProjeto.WebProjeto.InsertFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertFuncResponse> InsertFuncAsync(DesktopProjeto.WebProjeto.InsertFuncRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProj", ReplyAction="*")]
        DesktopProjeto.WebProjeto.InsertProjResponse InsertProj(DesktopProjeto.WebProjeto.InsertProjRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProj", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertProjResponse> InsertProjAsync(DesktopProjeto.WebProjeto.InsertProjRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFuncProj", ReplyAction="*")]
        bool InsertFuncProj(int idf, int idp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFuncProj", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertFuncProjAsync(int idf, int idp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDependente", ReplyAction="*")]
        bool ExcluiDependente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDependente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiDependenteAsync(int id);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDependente", ReplyAction="*")]
        DesktopProjeto.WebProjeto.UpdateDependenteResponse UpdateDependente(DesktopProjeto.WebProjeto.UpdateDependenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDependente", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateDependenteResponse> UpdateDependenteAsync(DesktopProjeto.WebProjeto.UpdateDependenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDpto", ReplyAction="*")]
        bool ExcluiDpto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiDpto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiDptoAsync(int id);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDpto", ReplyAction="*")]
        DesktopProjeto.WebProjeto.UpdateDptoResponse UpdateDpto(DesktopProjeto.WebProjeto.UpdateDptoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDpto", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateDptoResponse> UpdateDptoAsync(DesktopProjeto.WebProjeto.UpdateDptoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFunc", ReplyAction="*")]
        bool ExcluiFunc(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiFuncAsync(int id);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFunc", ReplyAction="*")]
        DesktopProjeto.WebProjeto.UpdateFuncResponse UpdateFunc(DesktopProjeto.WebProjeto.UpdateFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateFuncResponse> UpdateFuncAsync(DesktopProjeto.WebProjeto.UpdateFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiProjeto", ReplyAction="*")]
        bool ExcluiProjeto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiProjetoAsync(int id);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProjeto", ReplyAction="*")]
        DesktopProjeto.WebProjeto.UpdateProjetoResponse UpdateProjeto(DesktopProjeto.WebProjeto.UpdateProjetoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateProjetoResponse> UpdateProjetoAsync(DesktopProjeto.WebProjeto.UpdateProjetoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFuncProjeto", ReplyAction="*")]
        bool UpdateFuncProjeto(int idf, int idp, int aidf, int aidp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFuncProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateFuncProjetoAsync(int idf, int idp, int aidf, int aidp, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFuncProjeto", ReplyAction="*")]
        bool ExcluiFuncProjeto(int idf, int idp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluiFuncProjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExcluiFuncProjetoAsync(int idf, int idp);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDepartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDepart", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertDepartRequestBody Body;
        
        public InsertDepartRequest() {
        }
        
        public InsertDepartRequest(DesktopProjeto.WebProjeto.InsertDepartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDepartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string local;
        
        public InsertDepartRequestBody() {
        }
        
        public InsertDepartRequestBody(int id, string nome, string local) {
            this.id = id;
            this.nome = nome;
            this.local = local;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDepartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDepartResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertDepartResponseBody Body;
        
        public InsertDepartResponse() {
        }
        
        public InsertDepartResponse(DesktopProjeto.WebProjeto.InsertDepartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDepartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertDepartResult;
        
        public InsertDepartResponseBody() {
        }
        
        public InsertDepartResponseBody(bool InsertDepartResult) {
            this.InsertDepartResult = InsertDepartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDependenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDependente", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertDependenteRequestBody Body;
        
        public InsertDependenteRequest() {
        }
        
        public InsertDependenteRequest(DesktopProjeto.WebProjeto.InsertDependenteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDependenteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idf;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string parente;
        
        public InsertDependenteRequestBody() {
        }
        
        public InsertDependenteRequestBody(int idf, int idd, string nome, string parente) {
            this.idf = idf;
            this.idd = idd;
            this.nome = nome;
            this.parente = parente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDependenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDependenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertDependenteResponseBody Body;
        
        public InsertDependenteResponse() {
        }
        
        public InsertDependenteResponse(DesktopProjeto.WebProjeto.InsertDependenteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDependenteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertDependenteResult;
        
        public InsertDependenteResponseBody() {
        }
        
        public InsertDependenteResponseBody(bool InsertDependenteResult) {
            this.InsertDependenteResult = InsertDependenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFuncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFunc", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertFuncRequestBody Body;
        
        public InsertFuncRequest() {
        }
        
        public InsertFuncRequest(DesktopProjeto.WebProjeto.InsertFuncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertFuncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string end;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefone;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal salario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int idpto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int idptoger;
        
        public InsertFuncRequestBody() {
        }
        
        public InsertFuncRequestBody(int id, string nome, string end, string telefone, decimal salario, int idpto, int idptoger) {
            this.id = id;
            this.nome = nome;
            this.end = end;
            this.telefone = telefone;
            this.salario = salario;
            this.idpto = idpto;
            this.idptoger = idptoger;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFuncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFuncResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertFuncResponseBody Body;
        
        public InsertFuncResponse() {
        }
        
        public InsertFuncResponse(DesktopProjeto.WebProjeto.InsertFuncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertFuncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertFuncResult;
        
        public InsertFuncResponseBody() {
        }
        
        public InsertFuncResponseBody(bool InsertFuncResult) {
            this.InsertFuncResult = InsertFuncResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProjRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProj", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertProjRequestBody Body;
        
        public InsertProjRequest() {
        }
        
        public InsertProjRequest(DesktopProjeto.WebProjeto.InsertProjRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertProjRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string verba;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idpto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int cpffunc;
        
        public InsertProjRequestBody() {
        }
        
        public InsertProjRequestBody(int id, string nome, string tipo, string verba, int idpto, int cpffunc) {
            this.id = id;
            this.nome = nome;
            this.tipo = tipo;
            this.verba = verba;
            this.idpto = idpto;
            this.cpffunc = cpffunc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProjResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProjResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.InsertProjResponseBody Body;
        
        public InsertProjResponse() {
        }
        
        public InsertProjResponse(DesktopProjeto.WebProjeto.InsertProjResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertProjResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertProjResult;
        
        public InsertProjResponseBody() {
        }
        
        public InsertProjResponseBody(bool InsertProjResult) {
            this.InsertProjResult = InsertProjResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDependenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDependente", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateDependenteRequestBody Body;
        
        public UpdateDependenteRequest() {
        }
        
        public UpdateDependenteRequest(DesktopProjeto.WebProjeto.UpdateDependenteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDependenteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string par;
        
        public UpdateDependenteRequestBody() {
        }
        
        public UpdateDependenteRequestBody(int id, string nome, string par) {
            this.id = id;
            this.nome = nome;
            this.par = par;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDependenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDependenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateDependenteResponseBody Body;
        
        public UpdateDependenteResponse() {
        }
        
        public UpdateDependenteResponse(DesktopProjeto.WebProjeto.UpdateDependenteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDependenteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateDependenteResult;
        
        public UpdateDependenteResponseBody() {
        }
        
        public UpdateDependenteResponseBody(bool UpdateDependenteResult) {
            this.UpdateDependenteResult = UpdateDependenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDptoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDpto", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateDptoRequestBody Body;
        
        public UpdateDptoRequest() {
        }
        
        public UpdateDptoRequest(DesktopProjeto.WebProjeto.UpdateDptoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDptoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string local;
        
        public UpdateDptoRequestBody() {
        }
        
        public UpdateDptoRequestBody(int id, string nome, string local) {
            this.id = id;
            this.nome = nome;
            this.local = local;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDptoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDptoResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateDptoResponseBody Body;
        
        public UpdateDptoResponse() {
        }
        
        public UpdateDptoResponse(DesktopProjeto.WebProjeto.UpdateDptoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDptoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateDptoResult;
        
        public UpdateDptoResponseBody() {
        }
        
        public UpdateDptoResponseBody(bool UpdateDptoResult) {
            this.UpdateDptoResult = UpdateDptoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFuncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFunc", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateFuncRequestBody Body;
        
        public UpdateFuncRequest() {
        }
        
        public UpdateFuncRequest(DesktopProjeto.WebProjeto.UpdateFuncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFuncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string end;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal sal;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int dp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int dpger;
        
        public UpdateFuncRequestBody() {
        }
        
        public UpdateFuncRequestBody(int id, string nome, string end, string tel, decimal sal, int dp, int dpger) {
            this.id = id;
            this.nome = nome;
            this.end = end;
            this.tel = tel;
            this.sal = sal;
            this.dp = dp;
            this.dpger = dpger;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFuncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFuncResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateFuncResponseBody Body;
        
        public UpdateFuncResponse() {
        }
        
        public UpdateFuncResponse(DesktopProjeto.WebProjeto.UpdateFuncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFuncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateFuncResult;
        
        public UpdateFuncResponseBody() {
        }
        
        public UpdateFuncResponseBody(bool UpdateFuncResult) {
            this.UpdateFuncResult = UpdateFuncResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProjetoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProjeto", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateProjetoRequestBody Body;
        
        public UpdateProjetoRequest() {
        }
        
        public UpdateProjetoRequest(DesktopProjeto.WebProjeto.UpdateProjetoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProjetoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool conc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string verba;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int dp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int cdf;
        
        public UpdateProjetoRequestBody() {
        }
        
        public UpdateProjetoRequestBody(int id, bool conc, string nome, string tipo, string verba, int dp, int cdf) {
            this.id = id;
            this.conc = conc;
            this.nome = nome;
            this.tipo = tipo;
            this.verba = verba;
            this.dp = dp;
            this.cdf = cdf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProjetoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProjetoResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopProjeto.WebProjeto.UpdateProjetoResponseBody Body;
        
        public UpdateProjetoResponse() {
        }
        
        public UpdateProjetoResponse(DesktopProjeto.WebProjeto.UpdateProjetoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProjetoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateProjetoResult;
        
        public UpdateProjetoResponseBody() {
        }
        
        public UpdateProjetoResponseBody(bool UpdateProjetoResult) {
            this.UpdateProjetoResult = UpdateProjetoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DesktopProjeto.WebProjeto.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DesktopProjeto.WebProjeto.WebService1Soap>, DesktopProjeto.WebProjeto.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.InsertDepartResponse DesktopProjeto.WebProjeto.WebService1Soap.InsertDepart(DesktopProjeto.WebProjeto.InsertDepartRequest request) {
            return base.Channel.InsertDepart(request);
        }
        
        public bool InsertDepart(int id, string nome, string local) {
            DesktopProjeto.WebProjeto.InsertDepartRequest inValue = new DesktopProjeto.WebProjeto.InsertDepartRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertDepartRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.local = local;
            DesktopProjeto.WebProjeto.InsertDepartResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertDepart(inValue);
            return retVal.Body.InsertDepartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertDepartResponse> DesktopProjeto.WebProjeto.WebService1Soap.InsertDepartAsync(DesktopProjeto.WebProjeto.InsertDepartRequest request) {
            return base.Channel.InsertDepartAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertDepartResponse> InsertDepartAsync(int id, string nome, string local) {
            DesktopProjeto.WebProjeto.InsertDepartRequest inValue = new DesktopProjeto.WebProjeto.InsertDepartRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertDepartRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.local = local;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertDepartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.InsertDependenteResponse DesktopProjeto.WebProjeto.WebService1Soap.InsertDependente(DesktopProjeto.WebProjeto.InsertDependenteRequest request) {
            return base.Channel.InsertDependente(request);
        }
        
        public bool InsertDependente(int idf, int idd, string nome, string parente) {
            DesktopProjeto.WebProjeto.InsertDependenteRequest inValue = new DesktopProjeto.WebProjeto.InsertDependenteRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertDependenteRequestBody();
            inValue.Body.idf = idf;
            inValue.Body.idd = idd;
            inValue.Body.nome = nome;
            inValue.Body.parente = parente;
            DesktopProjeto.WebProjeto.InsertDependenteResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertDependente(inValue);
            return retVal.Body.InsertDependenteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertDependenteResponse> DesktopProjeto.WebProjeto.WebService1Soap.InsertDependenteAsync(DesktopProjeto.WebProjeto.InsertDependenteRequest request) {
            return base.Channel.InsertDependenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertDependenteResponse> InsertDependenteAsync(int idf, int idd, string nome, string parente) {
            DesktopProjeto.WebProjeto.InsertDependenteRequest inValue = new DesktopProjeto.WebProjeto.InsertDependenteRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertDependenteRequestBody();
            inValue.Body.idf = idf;
            inValue.Body.idd = idd;
            inValue.Body.nome = nome;
            inValue.Body.parente = parente;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertDependenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.InsertFuncResponse DesktopProjeto.WebProjeto.WebService1Soap.InsertFunc(DesktopProjeto.WebProjeto.InsertFuncRequest request) {
            return base.Channel.InsertFunc(request);
        }
        
        public bool InsertFunc(int id, string nome, string end, string telefone, decimal salario, int idpto, int idptoger) {
            DesktopProjeto.WebProjeto.InsertFuncRequest inValue = new DesktopProjeto.WebProjeto.InsertFuncRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertFuncRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.end = end;
            inValue.Body.telefone = telefone;
            inValue.Body.salario = salario;
            inValue.Body.idpto = idpto;
            inValue.Body.idptoger = idptoger;
            DesktopProjeto.WebProjeto.InsertFuncResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertFunc(inValue);
            return retVal.Body.InsertFuncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertFuncResponse> DesktopProjeto.WebProjeto.WebService1Soap.InsertFuncAsync(DesktopProjeto.WebProjeto.InsertFuncRequest request) {
            return base.Channel.InsertFuncAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertFuncResponse> InsertFuncAsync(int id, string nome, string end, string telefone, decimal salario, int idpto, int idptoger) {
            DesktopProjeto.WebProjeto.InsertFuncRequest inValue = new DesktopProjeto.WebProjeto.InsertFuncRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertFuncRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.end = end;
            inValue.Body.telefone = telefone;
            inValue.Body.salario = salario;
            inValue.Body.idpto = idpto;
            inValue.Body.idptoger = idptoger;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertFuncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.InsertProjResponse DesktopProjeto.WebProjeto.WebService1Soap.InsertProj(DesktopProjeto.WebProjeto.InsertProjRequest request) {
            return base.Channel.InsertProj(request);
        }
        
        public bool InsertProj(int id, string nome, string tipo, string verba, int idpto, int cpffunc) {
            DesktopProjeto.WebProjeto.InsertProjRequest inValue = new DesktopProjeto.WebProjeto.InsertProjRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertProjRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.tipo = tipo;
            inValue.Body.verba = verba;
            inValue.Body.idpto = idpto;
            inValue.Body.cpffunc = cpffunc;
            DesktopProjeto.WebProjeto.InsertProjResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertProj(inValue);
            return retVal.Body.InsertProjResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertProjResponse> DesktopProjeto.WebProjeto.WebService1Soap.InsertProjAsync(DesktopProjeto.WebProjeto.InsertProjRequest request) {
            return base.Channel.InsertProjAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.InsertProjResponse> InsertProjAsync(int id, string nome, string tipo, string verba, int idpto, int cpffunc) {
            DesktopProjeto.WebProjeto.InsertProjRequest inValue = new DesktopProjeto.WebProjeto.InsertProjRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.InsertProjRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.tipo = tipo;
            inValue.Body.verba = verba;
            inValue.Body.idpto = idpto;
            inValue.Body.cpffunc = cpffunc;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).InsertProjAsync(inValue);
        }
        
        public bool InsertFuncProj(int idf, int idp, int hora) {
            return base.Channel.InsertFuncProj(idf, idp, hora);
        }
        
        public System.Threading.Tasks.Task<bool> InsertFuncProjAsync(int idf, int idp, int hora) {
            return base.Channel.InsertFuncProjAsync(idf, idp, hora);
        }
        
        public bool ExcluiDependente(int id) {
            return base.Channel.ExcluiDependente(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiDependenteAsync(int id) {
            return base.Channel.ExcluiDependenteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.UpdateDependenteResponse DesktopProjeto.WebProjeto.WebService1Soap.UpdateDependente(DesktopProjeto.WebProjeto.UpdateDependenteRequest request) {
            return base.Channel.UpdateDependente(request);
        }
        
        public bool UpdateDependente(int id, string nome, string par) {
            DesktopProjeto.WebProjeto.UpdateDependenteRequest inValue = new DesktopProjeto.WebProjeto.UpdateDependenteRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateDependenteRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.par = par;
            DesktopProjeto.WebProjeto.UpdateDependenteResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateDependente(inValue);
            return retVal.Body.UpdateDependenteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateDependenteResponse> DesktopProjeto.WebProjeto.WebService1Soap.UpdateDependenteAsync(DesktopProjeto.WebProjeto.UpdateDependenteRequest request) {
            return base.Channel.UpdateDependenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateDependenteResponse> UpdateDependenteAsync(int id, string nome, string par) {
            DesktopProjeto.WebProjeto.UpdateDependenteRequest inValue = new DesktopProjeto.WebProjeto.UpdateDependenteRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateDependenteRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.par = par;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateDependenteAsync(inValue);
        }
        
        public bool ExcluiDpto(int id) {
            return base.Channel.ExcluiDpto(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiDptoAsync(int id) {
            return base.Channel.ExcluiDptoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.UpdateDptoResponse DesktopProjeto.WebProjeto.WebService1Soap.UpdateDpto(DesktopProjeto.WebProjeto.UpdateDptoRequest request) {
            return base.Channel.UpdateDpto(request);
        }
        
        public bool UpdateDpto(int id, string nome, string local) {
            DesktopProjeto.WebProjeto.UpdateDptoRequest inValue = new DesktopProjeto.WebProjeto.UpdateDptoRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateDptoRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.local = local;
            DesktopProjeto.WebProjeto.UpdateDptoResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateDpto(inValue);
            return retVal.Body.UpdateDptoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateDptoResponse> DesktopProjeto.WebProjeto.WebService1Soap.UpdateDptoAsync(DesktopProjeto.WebProjeto.UpdateDptoRequest request) {
            return base.Channel.UpdateDptoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateDptoResponse> UpdateDptoAsync(int id, string nome, string local) {
            DesktopProjeto.WebProjeto.UpdateDptoRequest inValue = new DesktopProjeto.WebProjeto.UpdateDptoRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateDptoRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.local = local;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateDptoAsync(inValue);
        }
        
        public bool ExcluiFunc(int id) {
            return base.Channel.ExcluiFunc(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiFuncAsync(int id) {
            return base.Channel.ExcluiFuncAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.UpdateFuncResponse DesktopProjeto.WebProjeto.WebService1Soap.UpdateFunc(DesktopProjeto.WebProjeto.UpdateFuncRequest request) {
            return base.Channel.UpdateFunc(request);
        }
        
        public bool UpdateFunc(int id, string nome, string end, string tel, decimal sal, int dp, int dpger) {
            DesktopProjeto.WebProjeto.UpdateFuncRequest inValue = new DesktopProjeto.WebProjeto.UpdateFuncRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateFuncRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.end = end;
            inValue.Body.tel = tel;
            inValue.Body.sal = sal;
            inValue.Body.dp = dp;
            inValue.Body.dpger = dpger;
            DesktopProjeto.WebProjeto.UpdateFuncResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateFunc(inValue);
            return retVal.Body.UpdateFuncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateFuncResponse> DesktopProjeto.WebProjeto.WebService1Soap.UpdateFuncAsync(DesktopProjeto.WebProjeto.UpdateFuncRequest request) {
            return base.Channel.UpdateFuncAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateFuncResponse> UpdateFuncAsync(int id, string nome, string end, string tel, decimal sal, int dp, int dpger) {
            DesktopProjeto.WebProjeto.UpdateFuncRequest inValue = new DesktopProjeto.WebProjeto.UpdateFuncRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateFuncRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.end = end;
            inValue.Body.tel = tel;
            inValue.Body.sal = sal;
            inValue.Body.dp = dp;
            inValue.Body.dpger = dpger;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateFuncAsync(inValue);
        }
        
        public bool ExcluiProjeto(int id) {
            return base.Channel.ExcluiProjeto(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiProjetoAsync(int id) {
            return base.Channel.ExcluiProjetoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopProjeto.WebProjeto.UpdateProjetoResponse DesktopProjeto.WebProjeto.WebService1Soap.UpdateProjeto(DesktopProjeto.WebProjeto.UpdateProjetoRequest request) {
            return base.Channel.UpdateProjeto(request);
        }
        
        public bool UpdateProjeto(int id, bool conc, string nome, string tipo, string verba, int dp, int cdf) {
            DesktopProjeto.WebProjeto.UpdateProjetoRequest inValue = new DesktopProjeto.WebProjeto.UpdateProjetoRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateProjetoRequestBody();
            inValue.Body.id = id;
            inValue.Body.conc = conc;
            inValue.Body.nome = nome;
            inValue.Body.tipo = tipo;
            inValue.Body.verba = verba;
            inValue.Body.dp = dp;
            inValue.Body.cdf = cdf;
            DesktopProjeto.WebProjeto.UpdateProjetoResponse retVal = ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateProjeto(inValue);
            return retVal.Body.UpdateProjetoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateProjetoResponse> DesktopProjeto.WebProjeto.WebService1Soap.UpdateProjetoAsync(DesktopProjeto.WebProjeto.UpdateProjetoRequest request) {
            return base.Channel.UpdateProjetoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopProjeto.WebProjeto.UpdateProjetoResponse> UpdateProjetoAsync(int id, bool conc, string nome, string tipo, string verba, int dp, int cdf) {
            DesktopProjeto.WebProjeto.UpdateProjetoRequest inValue = new DesktopProjeto.WebProjeto.UpdateProjetoRequest();
            inValue.Body = new DesktopProjeto.WebProjeto.UpdateProjetoRequestBody();
            inValue.Body.id = id;
            inValue.Body.conc = conc;
            inValue.Body.nome = nome;
            inValue.Body.tipo = tipo;
            inValue.Body.verba = verba;
            inValue.Body.dp = dp;
            inValue.Body.cdf = cdf;
            return ((DesktopProjeto.WebProjeto.WebService1Soap)(this)).UpdateProjetoAsync(inValue);
        }
        
        public bool UpdateFuncProjeto(int idf, int idp, int aidf, int aidp, int hora) {
            return base.Channel.UpdateFuncProjeto(idf, idp, aidf, aidp, hora);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFuncProjetoAsync(int idf, int idp, int aidf, int aidp, int hora) {
            return base.Channel.UpdateFuncProjetoAsync(idf, idp, aidf, aidp, hora);
        }
        
        public bool ExcluiFuncProjeto(int idf, int idp) {
            return base.Channel.ExcluiFuncProjeto(idf, idp);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluiFuncProjetoAsync(int idf, int idp) {
            return base.Channel.ExcluiFuncProjetoAsync(idf, idp);
        }
    }
}
