/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saga;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Frm_saga extends javax.swing.JFrame {

    Connection con; // Conversa com o Banco
    PreparedStatement ps; // String da query formatada
    PreparedStatement ps1; // String da query formatada
    PreparedStatement ps0; // String da query formatada
    ResultSet rs0; // Retorno do banco
    ResultSet rs; // Retorno do banco
    int categoria;
    
    /**
     * Creates new form Frm_saga
     */
    public Frm_saga() {
        initComponents();
        getContentPane().setBackground(Color.getHSBColor(51,153,255));
        setLocationRelativeTo(null);
        try{
                con = Sagas_Class.conectar("root","root");
                ps = con.prepareStatement("select tb_user.nm_user, tb_user.cd_telefone, tb_users_type.nm_users_type from tb_user right join item_user_users_type"
                        + " on tb_user.cd_user = item_user_users_type.cd_user left join tb_users_type on item_user_users_type.cd_users_type = tb_users_type.cd_users_type");
                // receber os dados do banco
                rs = ps.executeQuery();
                // os dados estao em um bloco que precisa ser percorrido por um while
                while(rs.next()){//enquanto houver um registro válido
                    txt_lista.append("Nome: "+rs.getString("tb_user.nm_user")+", Telefone: "+rs.getString("tb_user.cd_telefone")+", Tipo: "+rs.getString("tb_users_type.nm_users_type")+"\n");
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Erro: "+ex.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        btn_logar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_logn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbl_confirma = new javax.swing.JLabel();
        txt_logs = new javax.swing.JPasswordField();
        btn_cadastrar = new javax.swing.JToggleButton();
        txt_nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_lista = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        btn_log = new javax.swing.JButton();
        txt_csenha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();

        jd_login.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jd_loginComponentHidden(evt);
            }
        });
        jd_login.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jd_loginWindowClosed(evt);
            }
        });

        btn_logar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_logar.setText("Logar");
        btn_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Senha:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("SAGA Login");

        txt_logn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_confirma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_logs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btn_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(62, 62, 62)
                        .addComponent(lbl_confirma)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_logn)
                            .addComponent(txt_logs))))
                .addContainerGap())
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_confirma))
                .addGap(31, 31, 31)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_logn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_logs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_logar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        btn_cadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        txt_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_nome.setMaximumSize(new java.awt.Dimension(10, 10));
        txt_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomeKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Telefone:");

        txt_telefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefoneKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Tipo:");

        cmb_tipo.setBackground(new java.awt.Color(153, 255, 255));
        cmb_tipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diretor", "Professor", "Aluno" }));

        txt_lista.setEditable(false);
        txt_lista.setColumns(20);
        txt_lista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_lista.setRows(5);
        jScrollPane1.setViewportView(txt_lista);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("SAGA Cadastro");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Senha:");

        txt_senha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_senhaKeyTyped(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_log.setText("Login");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        txt_csenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Confirmar Senha:");

        btn_update.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_update.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cadastrar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_csenha)
                                            .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmb_tipo, 0, 198, Short.MAX_VALUE)
                                            .addComponent(txt_senha))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn_log))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btn_update)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_csenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadastrar)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        if (txt_senha.getText().equals(txt_csenha.getText()) && txt_nome.getText() != "" && txt_telefone.getText() != "" && txt_senha.getText() != "")
    {
        String s = "";
        try {
            //Abrir a conexao
            con = Sagas_Class.conectar("root","root");
            // Para comparar
            ps0 = con.prepareStatement("select nm_user"
                        + " from tb_user where nm_user = ?");
            ps0.setString(1, txt_nome.getText());
            rs0 = ps0.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Frm_saga.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        try {
            while(rs0.next()){//enquanto houver um registro válido
                s = rs0.getString("tb_user.nm_user");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Frm_saga.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (s == ""){
            txt_lista.setText("");
            try{            
                con = Sagas_Class.conectar("root","root");
                //pré formatar a string da query
                ps = con.prepareStatement("insert into tb_user (cd_telefone, nm_user, cd_senha)"
                        + "values (?,?,?)");
                // definir os valores de cada índice (?)
                ps.setString(1, txt_telefone.getText());
                ps.setString(2, txt_nome.getText());
                ps.setString(3, txt_senha.getText());

                ps.execute();

                ps1 = con.prepareStatement("insert into item_user_users_type values"
                        + " ((select cd_user from tb_user where nm_user = ? and cd_telefone = ? and cd_senha = ?), ?)");            
                ps1.setString(1, txt_nome.getText());
                ps1.setString(2, txt_telefone.getText());
                ps1.setString(3, txt_senha.getText());
                ps1.setInt(4, cmb_tipo.getSelectedIndex()+1);

                ps1.execute();
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Erro: "+ex.getMessage());
            }

            try{
                con = Sagas_Class.conectar("root","root");
                ps = con.prepareStatement("select tb_user.nm_user, tb_user.cd_telefone, tb_users_type.nm_users_type from tb_user right join item_user_users_type"
                        + " on tb_user.cd_user = item_user_users_type.cd_user left join tb_users_type on item_user_users_type.cd_users_type = tb_users_type.cd_users_type");
                // receber os dados do banco
                rs = ps.executeQuery();
                // os dados estao em um bloco que precisa ser percorrido por um while
                while(rs.next()){//enquanto houver um registro válido
                    txt_lista.append("Nome: "+rs.getString("tb_user.nm_user")+", Telefone: "+rs.getString("tb_user.cd_telefone")+", Tipo: "+rs.getString("tb_users_type.nm_users_type")+"\n");
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Erro: "+ex.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuário já existente!");
        }
    }
        else{
            JOptionPane.showMessageDialog(null, "Por favor, preencha tudo corretamente!");
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeKeyTyped
        if(txt_nome.getText().length()>20){
            evt.consume();
        }
    }//GEN-LAST:event_txt_nomeKeyTyped

    private void txt_telefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefoneKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
        if(txt_telefone.getText().trim().length()>10){
            evt.consume();
        }
    }//GEN-LAST:event_txt_telefoneKeyTyped

    private void txt_senhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_senhaKeyTyped
        if(txt_senha.getText().length()>15){
            evt.consume();
        }
    }//GEN-LAST:event_txt_senhaKeyTyped

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
        jd_login.setVisible(true);
        jd_login.setLocationRelativeTo(null);
        jd_login.setSize(285, 230);
        jd_login.getContentPane().setBackground(Color.getHSBColor(51,153,255));
        this.setVisible(false);
    }//GEN-LAST:event_btn_logActionPerformed

    private void btn_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logarActionPerformed
        String passlog = "";
        try {
            //Abrir a conexao
            con = Sagas_Class.conectar("root","root");
            // Para comparar
            ps0 = con.prepareStatement("select nm_user"
                        + " from tb_user where nm_user = ? and cd_senha = ?");
            ps0.setString(1, txt_logn.getText());
            ps0.setString(2, txt_logs.getText());
            rs0 = ps0.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Frm_saga.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        try {
            while(rs0.next()){//enquanto houver um registro válido
                passlog = rs0.getString("nm_user");
                break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Frm_saga.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (passlog == ""){
            lbl_confirma.setBackground(Color.red);
            lbl_confirma.setText("Login Inválido!");
        }
        else{
            lbl_confirma.setBackground(Color.green);
            lbl_confirma.setText("Login Completo!");
            txt_logn.setText("");
            txt_logs.setText("");            
        }
    }//GEN-LAST:event_btn_logarActionPerformed

    private void jd_loginWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_loginWindowClosed
        
    }//GEN-LAST:event_jd_loginWindowClosed

    private void jd_loginComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jd_loginComponentHidden
        this.setVisible(true);
    }//GEN-LAST:event_jd_loginComponentHidden

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(true);
        jd_login.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_saga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_saga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_saga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_saga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_saga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_cadastrar;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_logar;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_login;
    private javax.swing.JLabel lbl_confirma;
    private javax.swing.JPasswordField txt_csenha;
    private javax.swing.JTextArea txt_lista;
    private javax.swing.JTextField txt_logn;
    private javax.swing.JPasswordField txt_logs;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
