/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exercicio7;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lobin
 */
public class ExercicioRM04698 extends javax.swing.JFrame {
    
    DefaultListModel lista;
    String [] cadastro;
    ArrayList<Cadastro> listagem;
    
    /**
     * Creates new form ExercicioRM04698
     */
    public ExercicioRM04698() {
        initComponents();
        listagem = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgJob = new javax.swing.ButtonGroup();
        dlgRetorno = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstResultados1 = new javax.swing.JList<>();
        btnPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResultados = new javax.swing.JList<>();
        btnAdicionar = new javax.swing.JButton();
        pnlFuncionario = new javax.swing.JPanel();
        rdbPj = new javax.swing.JRadioButton();
        rdbClt = new javax.swing.JRadioButton();
        lblTipo = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox();
        cmbSetor = new javax.swing.JComboBox();
        lblSetor = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnExibir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        lstResultados1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado da Busca", 0, 0, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(204, 0, 51))); // NOI18N
        lstResultados1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lstResultados1.setForeground(new java.awt.Color(0, 51, 153));
        lstResultados1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstResultados1);

        javax.swing.GroupLayout dlgRetornoLayout = new javax.swing.GroupLayout(dlgRetorno.getContentPane());
        dlgRetorno.getContentPane().setLayout(dlgRetornoLayout);
        dlgRetornoLayout.setHorizontalGroup(
            dlgRetornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRetornoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgRetornoLayout.setVerticalGroup(
            dlgRetornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRetornoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPesquisa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPesquisa.setText("Pesquisa");
        btnPesquisa.setBorder(null);
        btnPesquisa.setBorderPainted(false);
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstResultados);

        btnAdicionar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        pnlFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Novo Funcionário", 0, 0, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        pnlFuncionario.setToolTipText("Adicionar Novo Funcionário");
        pnlFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btgJob.add(rdbPj);
        rdbPj.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdbPj.setText("PJ");

        btgJob.add(rdbClt);
        rdbClt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdbClt.setText("CLT");

        lblTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTipo.setText("Tipo");

        lblCargo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCargo.setText("Cargo");

        cmbCargo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente", "Office-Boy", "Secretária", "Diretor", "Analista", "Quebra-galho." }));

        cmbSetor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Financeiro", "RH", "Administração", "TI", "Vendas" }));

        lblSetor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSetor.setText("Setor");

        lblNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlFuncionarioLayout = new javax.swing.GroupLayout(pnlFuncionario);
        pnlFuncionario.setLayout(pnlFuncionarioLayout);
        pnlFuncionarioLayout.setHorizontalGroup(
            pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncionarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                        .addComponent(lblCargo)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addComponent(rdbClt)
                        .addGap(18, 18, 18)
                        .addComponent(rdbPj))
                    .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                        .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblSetor))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlFuncionarioLayout.setVerticalGroup(
            pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSetor)
                    .addComponent(cmbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rdbClt)
                    .addComponent(rdbPj))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btnExibir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnExibir.setText("Exibir");

        btnLimpar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnExibir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExibir)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(pnlFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        String nome = JOptionPane.showInputDialog("Digite um nome para buscar");
        if(nome!=null && nome.length()>=2){
            buscar(nome);
        }
        
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        Cadastro c = new Cadastro(txtNome.getText(), ""+cmbSetor.getSelectedItem(), ""+cmbCargo.getSelectedItem(), rdbClt.isSelected());
        listagem.add(c);
        JOptionPane.showMessageDialog(this, "Cadastro finalizado com sucesso");
        atualizaLista();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        listagem.clear();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicioRM04698.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicioRM04698.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicioRM04698.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicioRM04698.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicioRM04698().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgJob;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExibir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JComboBox cmbCargo;
    private javax.swing.JComboBox cmbSetor;
    private javax.swing.JDialog dlgRetorno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSetor;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JList<String> lstResultados;
    private javax.swing.JList<String> lstResultados1;
    private javax.swing.JPanel pnlFuncionario;
    private javax.swing.JRadioButton rdbClt;
    private javax.swing.JRadioButton rdbPj;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void buscar(String nome) {
        DefaultListModel busca = new DefaultListModel();
        
        for (Cadastro z: listagem){
            if (z.getNome().toUpperCase().contains(nome.toUpperCase())){
                busca.addElement("Nome: "+z.getNome()+", Setor: "+z.getSetor()+", Tipo: "+((z.isTipo())?"CLT":"PJ")+", Cargo: "+z.getCargo());
            }
        }
        lstResultados.setModel(busca);
    }

    private void atualizaLista() {
        DefaultListModel lista = (DefaultListModel)lstResultados.getModel();
        lista.clear();
        //For avançado..
        for(Cadastro x: listagem){
            lista.addElement("Nome: "+x.getNome()+", Setor: "+x.getSetor()+", Tipo: "+((x.isTipo())?"CLT":"PJ")+", Cargo: "+x.getCargo());
        }
    }
}