/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forca;

/**
 *
 * @author Aluno
 */
public class AForca extends javax.swing.JFrame {

    String palavra="rua";
    int i=0;
    /**
     * Creates new form AForca
     */
    public AForca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabeca = new javax.swing.JLabel();
        tronco = new javax.swing.JLabel();
        maodireita = new javax.swing.JLabel();
        maoesquerda = new javax.swing.JLabel();
        peesquerdo = new javax.swing.JLabel();
        pedireito = new javax.swing.JLabel();
        lbl_forca = new javax.swing.JLabel();
        txtletra = new javax.swing.JTextField();
        lblpalavra = new javax.swing.JLabel();
        btnconfirmar = new javax.swing.JButton();
        traco1 = new javax.swing.JLabel();
        traco2 = new javax.swing.JLabel();
        traco3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(300, 300));

        cabeca.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        cabeca.setText("O");

        tronco.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        tronco.setText("|");

        maodireita.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        maodireita.setText("_");

        maoesquerda.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        maoesquerda.setText("_");

        peesquerdo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        peesquerdo.setText("/");

        pedireito.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        pedireito.setText("\\");

            lbl_forca.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
            lbl_forca.setText("Jogo da Forca");

            txtletra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            txtletra.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtletraActionPerformed(evt);
                }
            });

            lblpalavra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            lblpalavra.setText("Digite uma letra:");

            btnconfirmar.setText("CONFIRMAR");
            btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnconfirmarActionPerformed(evt);
                }
            });

            traco1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
            traco1.setText("-");

            traco2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
            traco2.setText("-");

            traco3.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
            traco3.setText("-");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(peesquerdo)
                                    .addGap(18, 18, 18)
                                    .addComponent(pedireito))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(maoesquerda)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(tronco)
                                            .addGap(10, 10, 10)
                                            .addComponent(maodireita))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(cabeca)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtletra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblpalavra)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(traco1)
                                                .addGap(18, 18, 18)
                                                .addComponent(traco2)
                                                .addGap(18, 18, 18)
                                                .addComponent(traco3))
                                            .addComponent(btnconfirmar))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(lbl_forca)))
                    .addContainerGap(42, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_forca)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cabeca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tronco))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(maoesquerda))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(maodireita)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblpalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtletra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnconfirmar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(peesquerdo)
                                .addComponent(pedireito))
                            .addGap(28, 28, 28))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(traco1)
                                .addComponent(traco2)
                                .addComponent(traco3))
                            .addContainerGap())))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtletraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtletraActionPerformed

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        
        //Ao colocar uma palavra ele irá desabilitar a mesma e habilitar a letra
                String letra = txtletra.getText();
                letra = letra.substring(0);
                if(letra.equals("r") || letra.equals("u") || letra.equals("a")){
                if(letra.equals("r")){
                    traco1.setText("R");
                }
                if (letra.equals("u")){
                   traco2.setText("U");
                }
                if(letra.equals("a")){
                    traco3.setText("A");
                }
                }
                else {
                        i++;
                        if (i==1){
                           cabeca.setText("X");
                        }
                        else if (i==2){
                            tronco.setText("X");
                        }
                        else if (i==3){
                            maoesquerda.setText("X");
                        }
                        else if (i==4){
                            maodireita.setText("X");
                        }
                        else if (i==5){
                            pedireito.setText("X");
                        }
                        else if (i==6){
                            peesquerdo.setText("X");
                            txtletra.disable();
                        }
                    }
    }//GEN-LAST:event_btnconfirmarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AForca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JLabel cabeca;
    private javax.swing.JLabel lbl_forca;
    private javax.swing.JLabel lblpalavra;
    private javax.swing.JLabel maodireita;
    private javax.swing.JLabel maoesquerda;
    private javax.swing.JLabel pedireito;
    private javax.swing.JLabel peesquerdo;
    private javax.swing.JLabel traco1;
    private javax.swing.JLabel traco2;
    private javax.swing.JLabel traco3;
    private javax.swing.JLabel tronco;
    private javax.swing.JTextField txtletra;
    // End of variables declaration//GEN-END:variables
}
