-- MySQL Script generated by MySQL Workbench
-- Mon Nov  6 22:40:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema c
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c` DEFAULT CHARACTER SET utf8 ;
USE `c` ;

-- -----------------------------------------------------
-- Table `c`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`tb_curso` (
  `cd_curso` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_curso` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cd_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `c`.`tb_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`tb_disciplina` (
  `cd_disciplina` INT NOT NULL AUTO_INCREMENT,
  `cd_curso` INT NULL,
  `nm_disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_disciplina`),
  INDEX `fk_disciplina_curso_idx` (`cd_curso`),
  CONSTRAINT `fk_disciplina_curso`
    FOREIGN KEY (`cd_curso`)
    REFERENCES `c`.`tb_curso` (`cd_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `c`.`tb_aviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`tb_aviso` (
  `cd_disciplina` INT(11) NULL DEFAULT NULL,
  `nm_aviso` VARCHAR(60) NOT NULL,
  `ds_aviso` TEXT NOT NULL,
  INDEX `fk_aviso_disciplina_idx` (`cd_disciplina`),
  CONSTRAINT `fk_aviso_disciplina`
    FOREIGN KEY (`cd_disciplina`)
    REFERENCES `c`.`tb_disciplina` (`cd_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `c`.`tb_tipo_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`tb_tipo_usuario` (
  `cd_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nm_tipo` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`cd_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `c`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`tb_usuario` (
  `cd_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `cd_tipo` INT(11) NOT NULL,
  `nm_usuario` VARCHAR(100) NOT NULL,
  `nm_senha` VARCHAR(60) NOT NULL,
  `nm_email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cd_usuario`),
  INDEX `fk_usuario_tipo` (`cd_tipo`),
  CONSTRAINT `fk_usuario_tipo`
    FOREIGN KEY (`cd_tipo`)
    REFERENCES `c`.`tb_tipo_usuario` (`cd_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `c`.`item_usuario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`item_usuario_curso` (
  `cd_usuario` INT NULL,
  `cd_curso` INT NULL,
  INDEX `fk_usuario_item_curso_idx` (`cd_curso`),
  INDEX `fk_curso_item_usuario_idx` (`cd_usuario`),
  CONSTRAINT `fk_curso_item_usuario`
    FOREIGN KEY (`cd_usuario`)
    REFERENCES `c`.`tb_usuario` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_item_curso`
    FOREIGN KEY (`cd_curso`)
    REFERENCES `c`.`tb_curso` (`cd_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c`.`item_usuario_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`item_usuario_disciplina` (
  `cd_professor` INT NULL,
  `cd_disciplina` INT NULL,
  INDEX `fk_disciplina_item_usuario_idx` (`cd_professor`),
  INDEX `fk_usuario_item_disciplina_idx` (`cd_disciplina`),
  CONSTRAINT `fk_disciplina_item_usuario`
    FOREIGN KEY (`cd_professor`)
    REFERENCES `c`.`tb_usuario` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_item_disciplina`
    FOREIGN KEY (`cd_disciplina`)
    REFERENCES `c`.`tb_disciplina` (`cd_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c`.`tb_anotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c`.`tb_anotacao` (
  `cd_usuario` INT NULL,
  `nm_anotacao` VARCHAR(100) NULL,
  `ds_anotacao` LONGTEXT NULL,
  INDEX `fk_anotacao_usuario_idx` (`cd_usuario`),
  CONSTRAINT `fk_anotacao_usuario`
    FOREIGN KEY (`cd_usuario`)
    REFERENCES `c`.`tb_usuario` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
