-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 23:58:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `ds_role` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `nascimento` DATE NULL,
  `email` VARCHAR(100) NULL,
  `foto_user` BLOB NULL,
  `cpf` VARCHAR(12) NULL,
  `rg` VARCHAR(10) NULL,
  `password` VARCHAR(30) NULL,
  `contato1` VARCHAR(45) NULL,
  `contato2` VARCHAR(45) NULL,
  `responsavel` VARCHAR(200) NULL,
  `contato_responsavel` VARCHAR(45) NULL,
  `email_responsavel` VARCHAR(100) NULL,
  `cpf_responsavel` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `ds_permission` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role_user` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_user_users_idx` (`users_id` ASC),
  INDEX `fk_role_user_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_role_user_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_user_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permission_role` (
  `id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  `permissions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_permission_role_roles1_idx` (`roles_id` ASC),
  INDEX `fk_permission_role_permissions1_idx` (`permissions_id` ASC),
  CONSTRAINT `fk_permission_role_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_role_permissions1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `sg_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidades` (
  `id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidades_estados1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidades_id` INT NOT NULL,
  `nm_rua` VARCHAR(200) NULL,
  `cd_num_residencia` VARCHAR(10) NULL,
  `bairro` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enderecos_cidades1_idx` (`cidades_id` ASC),
  CONSTRAINT `fk_enderecos_cidades1`
    FOREIGN KEY (`cidades_id`)
    REFERENCES `mydb`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco_user` (
  `id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  INDEX `fk_endereco_user_endereco1_idx` (`endereco_id` ASC),
  INDEX `fk_endereco_user_users1_idx` (`users_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_endereco_user_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_user_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `ds_curso` VARCHAR(300) NULL,
  `qt_carga_horaria` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplinas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  `ds_disciplina` VARCHAR(300) NULL,
  `carga_horario_disciplina` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turnos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ds_turno` TEXT NULL COMMENT 'aqui poderá dizer horario de inicio e fim, e descrever horarios de intervalo e etc, caso seja uma instituição integral por exemplo',
  `hr_inicio` TIME NULL,
  `hr_final` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `dt_inicio` DATE NULL,
  `dt_final` DATE NULL,
  `qt_user` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_curso` (
  `id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  `disciplinas_id` INT NOT NULL,
  `turnos_id` INT NOT NULL,
  `turmas_id` INT NOT NULL,
  INDEX `fk_disciplina_curso_cursos1_idx` (`cursos_id` ASC),
  INDEX `fk_disciplina_curso_disciplinas1_idx` (`disciplinas_id` ASC),
  INDEX `fk_disciplina_curso_turnos1_idx` (`turnos_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_disciplina_curso_turmas1_idx` (`turmas_id` ASC),
  CONSTRAINT `fk_disciplina_curso_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_curso_disciplinas1`
    FOREIGN KEY (`disciplinas_id`)
    REFERENCES `mydb`.`disciplinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_curso_turnos1`
    FOREIGN KEY (`turnos_id`)
    REFERENCES `mydb`.`turnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_curso_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `mydb`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso_user` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `disciplina_curso_id` INT NOT NULL,
  INDEX `fk_curso_user_users1_idx` (`users_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_curso_user_disciplina_curso1_idx` (`disciplina_curso_id` ASC),
  CONSTRAINT `fk_curso_user_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_user_disciplina_curso1`
    FOREIGN KEY (`disciplina_curso_id`)
    REFERENCES `mydb`.`disciplina_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`arquivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ds_arquivo` VARCHAR(255) NULL,
  `arquivo_anexo` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_arquivos_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_arquivos_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notas` (
  `id` INT NOT NULL,
  `tipo_nota` VARCHAR(45) NULL,
  `nota` VARCHAR(4) NULL,
  `peso_nota` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota_disciplina` (
  `id` INT NOT NULL,
  `notas_id` INT NOT NULL,
  INDEX `fk_nota_user_notas1_idx` (`notas_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_nota_user_notas1`
    FOREIGN KEY (`notas_id`)
    REFERENCES `mydb`.`notas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aulas` (
  `id` INT NOT NULL,
  `disciplina_curso_id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `dt_aula` DATE NULL,
  `hr_inicio` TIME NULL,
  `hr_final` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aulas_disciplina_curso1_idx` (`disciplina_curso_id` ASC),
  CONSTRAINT `fk_aulas_disciplina_curso1`
    FOREIGN KEY (`disciplina_curso_id`)
    REFERENCES `mydb`.`disciplina_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`frequencia` (
  `id` INT NOT NULL,
  `dt_frequencia` DATE NULL,
  `status` TINYINT(1) NULL,
  `aulas_id` INT NOT NULL,
  `curso_user_id` INT NOT NULL,
  `justificar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_frequencia_aulas1_idx` (`aulas_id` ASC),
  INDEX `fk_frequencia_curso_user1_idx` (`curso_user_id` ASC),
  CONSTRAINT `fk_frequencia_aulas1`
    FOREIGN KEY (`aulas_id`)
    REFERENCES `mydb`.`aulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frequencia_curso_user1`
    FOREIGN KEY (`curso_user_id`)
    REFERENCES `mydb`.`curso_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`frequencia_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`frequencia_user` (
  `id` INT NOT NULL,
  `frequencia_id` INT NOT NULL,
  INDEX `fk_frequencia_user_frequencia1_idx` (`frequencia_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_frequencia_user_frequencia1`
    FOREIGN KEY (`frequencia_id`)
    REFERENCES `mydb`.`frequencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bate_papo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bate_papo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  `dt_inicio_bate_papo` DATE NULL,
  `dt_fim_bate_papo` DATE NULL,
  `limpar_historico` TINYINT(1) NULL,
  `disciplina_curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bate_papo_disciplina_curso1_idx` (`disciplina_curso_id` ASC),
  CONSTRAINT `fk_bate_papo_disciplina_curso1`
    FOREIGN KEY (`disciplina_curso_id`)
    REFERENCES `mydb`.`disciplina_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`messagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensagens` (
  `id` INT NOT NULL,
  `bate_papo_id` INT NOT NULL,
  `envio_mensagem` DATETIME NULL,
  `ds_conteudo_mensagem` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mensagens_bate_papo1_idx` (`bate_papo_id` ASC),
  CONSTRAINT `fk_mensagens_bate_papo1`
    FOREIGN KEY (`bate_papo_id`)
    REFERENCES `mydb`.`bate_papo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_user` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materiais` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ds_material` VARCHAR(255) NULL,
  `anexo_material` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`material_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`material_disciplina` (
  `id` INT NOT NULL,
  `materiais_id` INT NOT NULL,
  `disciplina_curso_id` INT NOT NULL,
  INDEX `fk_material_disciplina_materiais1_idx` (`materiais_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_material_disciplina_disciplina_curso1_idx` (`disciplina_curso_id` ASC),
  CONSTRAINT `fk_material_disciplina_materiais1`
    FOREIGN KEY (`materiais_id`)
    REFERENCES `mydb`.`materiais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_disciplina_disciplina_curso1`
    FOREIGN KEY (`disciplina_curso_id`)
    REFERENCES `mydb`.`disciplina_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`justificar_falta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`justificar_falta` (
  `id` INT NOT NULL,
  `ds_falta` TEXT NULL,
  `dt_falta` DATE NULL,
  `arquivo_falta` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lembretes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lembretes` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ds_lembrete` TEXT NULL,
  `dt_inicio` DATE NULL,
  `dt_final` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lembretes_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_lembretes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anotacoes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ds_anotacao` VARCHAR(200) NULL,
  `anotacao` TEXT NULL,
  `dt_anotacao` DATE NULL,
  `curso_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anotacoes_curso_user1_idx` (`curso_user_id` ASC),
  CONSTRAINT `fk_anotacoes_curso_user1`
    FOREIGN KEY (`curso_user_id`)
    REFERENCES `mydb`.`curso_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina_anotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_anotacao` (
  `id` INT NOT NULL,
  `anotacoes_id` INT NOT NULL,
  INDEX `fk_disciplina_anotacao_anotacoes1_idx` (`anotacoes_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_disciplina_anotacao_anotacoes1`
    FOREIGN KEY (`anotacoes_id`)
    REFERENCES `mydb`.`anotacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarefas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ds_tarefa` VARCHAR(300) NULL,
  `tarefa` TEXT NULL,
  `dt_tarefa` DATE NULL,
  `dt_inicio` DATE NULL,
  `dt_fim` DATE NULL,
  `curso_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarefas_curso_user1_idx` (`curso_user_id` ASC),
  CONSTRAINT `fk_tarefas_curso_user1`
    FOREIGN KEY (`curso_user_id`)
    REFERENCES `mydb`.`curso_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarefa_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarefa_disciplina` (
  `id` INT NOT NULL,
  `tarefas_id` INT NOT NULL,
  INDEX `fk_tarefa_disciplina_tarefas1_idx` (`tarefas_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tarefa_disciplina_tarefas1`
    FOREIGN KEY (`tarefas_id`)
    REFERENCES `mydb`.`tarefas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacoes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ds_avaliacao` VARCHAR(200) NULL,
  `dt_avaliacao` DATE NULL,
  `nota` VARCHAR(5) NULL,
  `curso_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacoes_curso_user1_idx` (`curso_user_id` ASC),
  CONSTRAINT `fk_avaliacoes_curso_user1`
    FOREIGN KEY (`curso_user_id`)
    REFERENCES `mydb`.`curso_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `id` INT NOT NULL,
  `ds_email` VARCHAR(200) NULL,
  `ds_senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avisos` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `noticia` TEXT NULL,
  `dt_noticia` DATE NULL,
  `anexo_noticia` BLOB NULL,
  `cursos_id` INT NOT NULL,
  `turmas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_noticias_users1_idx` (`users_id` ASC),
  INDEX `fk_avisos_cursos1_idx` (`cursos_id` ASC),
  INDEX `fk_avisos_turmas1_idx` (`turmas_id` ASC),
  CONSTRAINT `fk_noticias_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avisos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avisos_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `mydb`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formandos_user_curso_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formandos_user_curso_turma` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`disciplina_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_turma` (
  `id` INT NOT NULL,
  `turmas_id` INT NOT NULL,
  `disciplina_curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disciplina_turma_turmas1_idx` (`turmas_id` ASC),
  INDEX `fk_disciplina_turma_disciplina_curso1_idx` (`disciplina_curso_id` ASC),
  CONSTRAINT `fk_disciplina_turma_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `mydb`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_turma_disciplina_curso1`
    FOREIGN KEY (`disciplina_curso_id`)
    REFERENCES `mydb`.`disciplina_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
