/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo_pc1_layouts;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class Exemplo_PC1_Layouts extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo_PC1_Layouts
     */
    public Exemplo_PC1_Layouts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_oeste = new javax.swing.JButton();
        btn_leste = new javax.swing.JButton();
        btn_norte = new javax.swing.JButton();
        btn_sul = new javax.swing.JButton();
        lbl_centro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 200));
        setPreferredSize(new java.awt.Dimension(900, 700));

        btn_oeste.setText("Oeste");
        btn_oeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oesteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_oeste, java.awt.BorderLayout.LINE_START);

        btn_leste.setText("Leste");
        btn_leste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lesteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_leste, java.awt.BorderLayout.LINE_END);

        btn_norte.setText("Norte");
        btn_norte.setPreferredSize(new java.awt.Dimension(73, 40));
        btn_norte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_norteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_norte, java.awt.BorderLayout.PAGE_START);

        btn_sul.setText("Sul");
        btn_sul.setPreferredSize(new java.awt.Dimension(73, 40));
        btn_sul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sulActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sul, java.awt.BorderLayout.PAGE_END);

        lbl_centro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_centro.setOpaque(true);
        lbl_centro.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(lbl_centro, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 505, 295);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_norteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_norteActionPerformed
        lbl_centro.setText("REGIÃO NORTE");
        lbl_centro.setBackground(Color.blue);
    }//GEN-LAST:event_btn_norteActionPerformed

    private void btn_oesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oesteActionPerformed
        lbl_centro.setText("REGIÃO OESTE");
        lbl_centro.setBackground(Color.green);
    }//GEN-LAST:event_btn_oesteActionPerformed

    private void btn_lesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lesteActionPerformed
        lbl_centro.setText("REGIÃO LESTE");
        lbl_centro.setBackground(new Color(255, 127, 80));
    }//GEN-LAST:event_btn_lesteActionPerformed

    private void btn_sulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sulActionPerformed
        lbl_centro.setText("REGIÃO SUL");
        lbl_centro.setBackground(Color.orange);
    }//GEN-LAST:event_btn_sulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo_PC1_Layouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo_PC1_Layouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo_PC1_Layouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo_PC1_Layouts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo_PC1_Layouts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_leste;
    private javax.swing.JButton btn_norte;
    private javax.swing.JButton btn_oeste;
    private javax.swing.JButton btn_sul;
    private javax.swing.JLabel lbl_centro;
    // End of variables declaration//GEN-END:variables
}
