/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo_pc1_layouts;

import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JComponent;

/**
 *
 * @author Aluno
 */
public class jfLayoutFluxo extends javax.swing.JFrame {

    /**
     * Creates new form jfLayoutFluxo
     */
    public jfLayoutFluxo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_matriz = new javax.swing.JButton();
        btn_killer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        btn_matriz.setText("Matriz");
        btn_matriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matrizActionPerformed(evt);
            }
        });
        getContentPane().add(btn_matriz);

        btn_killer.setText("Killer");
        btn_killer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_killerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_killer);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_matrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matrizActionPerformed
        add(new JButton("nENEM"));
        validate(); //refresh no layout
    }//GEN-LAST:event_btn_matrizActionPerformed

    private void btn_killerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_killerActionPerformed
        //Ler todos os componentes em um vetor
        Component [] tudo = getContentPane().getComponents();
        //Remover os botões com texto 'nENEM'
        
        for (Component c: tudo){
            if (c instanceof JButton){
                if (((JButton)c).getText().equals("nENEM")){
                    remove(c);
                    break;
                }
            }
        }
        repaint();//redesenha a tela
        validate();
    }//GEN-LAST:event_btn_killerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfLayoutFluxo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfLayoutFluxo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfLayoutFluxo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfLayoutFluxo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfLayoutFluxo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_killer;
    private javax.swing.JButton btn_matriz;
    // End of variables declaration//GEN-END:variables
}
